// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module audio_clean_up_core (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ng_pass,
        st_gainL_i,
        st_gainL_o,
        st_gainL_o_ap_vld,
        st_gainR_i,
        st_gainR_o,
        st_gainR_o_ap_vld,
        st_gate_openL_i,
        st_gate_openL_o,
        st_gate_openL_o_ap_vld,
        st_gate_openR_i,
        st_gate_openR_o,
        st_gate_openR_o_ap_vld,
        st_th_open_amp,
        st_th_close_amp,
        st_a_attack,
        st_a_release,
        st_b_attack,
        st_b_release,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_7,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_6,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_5,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_4,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [0:0] ng_pass;
input  [23:0] st_gainL_i;
output  [23:0] st_gainL_o;
output   st_gainL_o_ap_vld;
input  [23:0] st_gainR_i;
output  [23:0] st_gainR_o;
output   st_gainR_o_ap_vld;
input  [0:0] st_gate_openL_i;
output  [0:0] st_gate_openL_o;
output   st_gate_openL_o_ap_vld;
input  [0:0] st_gate_openR_i;
output  [0:0] st_gate_openR_o;
output   st_gate_openR_o_ap_vld;
input  [33:0] st_th_open_amp;
input  [33:0] st_th_close_amp;
input  [23:0] st_a_attack;
input  [23:0] st_a_release;
input  [23:0] st_b_attack;
input  [23:0] st_b_release;
input  [31:0] noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_7;
input  [31:0] noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_6;
input  [2:0] noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_5;
input  [2:0] noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_4;
output  [31:0] noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3;
output   noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld;
output  [2:0] noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1;
output   noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld;
output  [31:0] noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2;
output   noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld;
output  [2:0] noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed;
output   noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[23:0] st_gainL_o;
reg st_gainL_o_ap_vld;
reg[23:0] st_gainR_o;
reg st_gainR_o_ap_vld;
reg[0:0] st_gate_openL_o;
reg st_gate_openL_o_ap_vld;
reg[0:0] st_gate_openR_o;
reg st_gate_openR_o_ap_vld;
reg[31:0] noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3;
reg noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld;
reg[2:0] noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1;
reg noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld;
reg[31:0] noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2;
reg noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld;
reg[2:0] noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed;
reg noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] ng_pass_read_read_fu_62_p2;
wire    grp_core_Pipeline_MAIN_LOOP_fu_68_ap_start;
wire    grp_core_Pipeline_MAIN_LOOP_fu_68_ap_done;
wire    grp_core_Pipeline_MAIN_LOOP_fu_68_ap_idle;
wire    grp_core_Pipeline_MAIN_LOOP_fu_68_ap_ready;
wire   [23:0] grp_core_Pipeline_MAIN_LOOP_fu_68_p_out;
wire    grp_core_Pipeline_MAIN_LOOP_fu_68_p_out_ap_vld;
wire   [23:0] grp_core_Pipeline_MAIN_LOOP_fu_68_p_out1;
wire    grp_core_Pipeline_MAIN_LOOP_fu_68_p_out1_ap_vld;
wire   [0:0] grp_core_Pipeline_MAIN_LOOP_fu_68_gateL_1_out;
wire    grp_core_Pipeline_MAIN_LOOP_fu_68_gateL_1_out_ap_vld;
wire   [0:0] grp_core_Pipeline_MAIN_LOOP_fu_68_gateR_1_out;
wire    grp_core_Pipeline_MAIN_LOOP_fu_68_gateR_1_out_ap_vld;
wire   [31:0] grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3;
wire    grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld;
wire   [2:0] grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1;
wire    grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld;
wire   [31:0] grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2;
wire    grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld;
wire   [2:0] grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed;
wire    grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld;
wire    grp_core_Pipeline_PASS_LOOP_fu_98_ap_start;
wire    grp_core_Pipeline_PASS_LOOP_fu_98_ap_done;
wire    grp_core_Pipeline_PASS_LOOP_fu_98_ap_idle;
wire    grp_core_Pipeline_PASS_LOOP_fu_98_ap_ready;
wire   [31:0] grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3;
wire    grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld;
wire   [2:0] grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1;
wire    grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld;
wire   [31:0] grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2;
wire    grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld;
wire   [2:0] grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed;
wire    grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld;
reg    grp_core_Pipeline_MAIN_LOOP_fu_68_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [31:0] noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_reg;
reg   [2:0] noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_reg;
reg   [31:0] noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_reg;
reg   [2:0] noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_reg;
reg    grp_core_Pipeline_PASS_LOOP_fu_98_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state3;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_core_Pipeline_MAIN_LOOP_fu_68_ap_start_reg = 1'b0;
#0 grp_core_Pipeline_PASS_LOOP_fu_98_ap_start_reg = 1'b0;
end

audio_clean_up_core_Pipeline_MAIN_LOOP grp_core_Pipeline_MAIN_LOOP_fu_68(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_core_Pipeline_MAIN_LOOP_fu_68_ap_start),
    .ap_done(grp_core_Pipeline_MAIN_LOOP_fu_68_ap_done),
    .ap_idle(grp_core_Pipeline_MAIN_LOOP_fu_68_ap_idle),
    .ap_ready(grp_core_Pipeline_MAIN_LOOP_fu_68_ap_ready),
    .gainR(st_gainR_i),
    .gainL(st_gainL_i),
    .gateL(st_gate_openL_i),
    .gateR(st_gate_openR_i),
    .noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_9(noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_6),
    .noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_8(noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_7),
    .noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_11(noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_4),
    .noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_10(noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_5),
    .th_close_amp(st_th_close_amp),
    .th_open_amp(st_th_open_amp),
    .a_att(st_a_attack),
    .a_rel(st_a_release),
    .b_att(st_b_attack),
    .b_rel(st_b_release),
    .p_out(grp_core_Pipeline_MAIN_LOOP_fu_68_p_out),
    .p_out_ap_vld(grp_core_Pipeline_MAIN_LOOP_fu_68_p_out_ap_vld),
    .p_out1(grp_core_Pipeline_MAIN_LOOP_fu_68_p_out1),
    .p_out1_ap_vld(grp_core_Pipeline_MAIN_LOOP_fu_68_p_out1_ap_vld),
    .gateL_1_out(grp_core_Pipeline_MAIN_LOOP_fu_68_gateL_1_out),
    .gateL_1_out_ap_vld(grp_core_Pipeline_MAIN_LOOP_fu_68_gateL_1_out_ap_vld),
    .gateR_1_out(grp_core_Pipeline_MAIN_LOOP_fu_68_gateR_1_out),
    .gateR_1_out_ap_vld(grp_core_Pipeline_MAIN_LOOP_fu_68_gateR_1_out_ap_vld),
    .noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3(grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3),
    .noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld(grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld),
    .noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1(grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1),
    .noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld(grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld),
    .noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2(grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2),
    .noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld(grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld),
    .noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed(grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed),
    .noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld(grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld)
);

audio_clean_up_core_Pipeline_PASS_LOOP grp_core_Pipeline_PASS_LOOP_fu_98(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_core_Pipeline_PASS_LOOP_fu_98_ap_start),
    .ap_done(grp_core_Pipeline_PASS_LOOP_fu_98_ap_done),
    .ap_idle(grp_core_Pipeline_PASS_LOOP_fu_98_ap_idle),
    .ap_ready(grp_core_Pipeline_PASS_LOOP_fu_98_ap_ready),
    .noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_9(noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_6),
    .noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_8(noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_7),
    .noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_11(noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_4),
    .noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_10(noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_5),
    .noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3(grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3),
    .noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld(grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld),
    .noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1(grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1),
    .noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld(grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld),
    .noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2(grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2),
    .noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld(grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld),
    .noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed(grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed),
    .noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld(grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_core_Pipeline_MAIN_LOOP_fu_68_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (ng_pass_read_read_fu_62_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_core_Pipeline_MAIN_LOOP_fu_68_ap_start_reg <= 1'b1;
        end else if ((grp_core_Pipeline_MAIN_LOOP_fu_68_ap_ready == 1'b1)) begin
            grp_core_Pipeline_MAIN_LOOP_fu_68_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_core_Pipeline_PASS_LOOP_fu_98_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (ng_pass_read_read_fu_62_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_core_Pipeline_PASS_LOOP_fu_98_ap_start_reg <= 1'b1;
        end else if ((grp_core_Pipeline_PASS_LOOP_fu_98_ap_ready == 1'b1)) begin
            grp_core_Pipeline_PASS_LOOP_fu_98_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld == 1'b1))) begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_reg <= grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1;
    end else if (((grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_reg <= grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld == 1'b1))) begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_reg <= grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2;
    end else if (((grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_reg <= grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld == 1'b1))) begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_reg <= grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3;
    end else if (((grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_reg <= grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld == 1'b1))) begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_reg <= grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed;
    end else if (((grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_reg <= grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_core_Pipeline_MAIN_LOOP_fu_68_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_core_Pipeline_PASS_LOOP_fu_98_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld == 1'b1))) begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed = grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed;
    end else if (((grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed = grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed;
    end else begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed = noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld == 1'b1))) begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1 = grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1;
    end else if (((grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1 = grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1;
    end else begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1 = noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld = grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld = grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld;
    end else begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld == 1'b1))) begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2 = grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2;
    end else if (((grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2 = grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2;
    end else begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2 = noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld = grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld = grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld;
    end else begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld == 1'b1))) begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3 = grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3;
    end else if (((grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3 = grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3;
    end else begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3 = noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld = grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld = grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld;
    end else begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld = grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld = grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld;
    end else begin
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ng_pass_read_read_fu_62_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        st_gainL_o = grp_core_Pipeline_MAIN_LOOP_fu_68_p_out1;
    end else begin
        st_gainL_o = st_gainL_i;
    end
end

always @ (*) begin
    if (((ng_pass_read_read_fu_62_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        st_gainL_o_ap_vld = 1'b1;
    end else begin
        st_gainL_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ng_pass_read_read_fu_62_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        st_gainR_o = grp_core_Pipeline_MAIN_LOOP_fu_68_p_out;
    end else begin
        st_gainR_o = st_gainR_i;
    end
end

always @ (*) begin
    if (((ng_pass_read_read_fu_62_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        st_gainR_o_ap_vld = 1'b1;
    end else begin
        st_gainR_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ng_pass_read_read_fu_62_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        st_gate_openL_o = grp_core_Pipeline_MAIN_LOOP_fu_68_gateL_1_out;
    end else begin
        st_gate_openL_o = st_gate_openL_i;
    end
end

always @ (*) begin
    if (((ng_pass_read_read_fu_62_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        st_gate_openL_o_ap_vld = 1'b1;
    end else begin
        st_gate_openL_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ng_pass_read_read_fu_62_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        st_gate_openR_o = grp_core_Pipeline_MAIN_LOOP_fu_68_gateR_1_out;
    end else begin
        st_gate_openR_o = st_gate_openR_i;
    end
end

always @ (*) begin
    if (((ng_pass_read_read_fu_62_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        st_gate_openR_o_ap_vld = 1'b1;
    end else begin
        st_gate_openR_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (ng_pass_read_read_fu_62_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if (((ap_start == 1'b1) & (ng_pass_read_read_fu_62_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_core_Pipeline_MAIN_LOOP_fu_68_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_core_Pipeline_PASS_LOOP_fu_98_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign grp_core_Pipeline_MAIN_LOOP_fu_68_ap_start = grp_core_Pipeline_MAIN_LOOP_fu_68_ap_start_reg;

assign grp_core_Pipeline_PASS_LOOP_fu_98_ap_start = grp_core_Pipeline_PASS_LOOP_fu_98_ap_start_reg;

assign ng_pass_read_read_fu_62_p2 = ng_pass;

endmodule //audio_clean_up_core
