// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module audio_clean_up_dc_cut_Pipeline_READ_LOOP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_dout,
        in_stream_empty_n,
        in_stream_read,
        in_buf_id_4_load_1_ce_out,
        in_buf_id_4_load_1_ce_out_ap_vld,
        in_buf_id_3_load_ce_out,
        in_buf_id_3_load_ce_out_ap_vld,
        in_buf_data_4_load_1_ce_out,
        in_buf_data_4_load_1_ce_out_ap_vld,
        in_buf_data_3_load_ce_out,
        in_buf_data_3_load_ce_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [34:0] in_stream_dout;
input   in_stream_empty_n;
output   in_stream_read;
output  [2:0] in_buf_id_4_load_1_ce_out;
output   in_buf_id_4_load_1_ce_out_ap_vld;
output  [2:0] in_buf_id_3_load_ce_out;
output   in_buf_id_3_load_ce_out_ap_vld;
output  [31:0] in_buf_data_4_load_1_ce_out;
output   in_buf_data_4_load_1_ce_out_ap_vld;
output  [31:0] in_buf_data_3_load_ce_out;
output   in_buf_data_3_load_ce_out_ap_vld;

reg ap_idle;
reg in_stream_read;
reg in_buf_id_4_load_1_ce_out_ap_vld;
reg in_buf_id_3_load_ce_out_ap_vld;
reg in_buf_data_4_load_1_ce_out_ap_vld;
reg in_buf_data_3_load_ce_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire   [0:0] tmp_4_nbreadreq_fu_94_p3;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_subdone;
reg   [0:0] ap_phi_mux_i_phi_fu_140_p4;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_stream_blk_n;
wire    ap_block_pp0_stage0;
reg   [0:0] i_reg_136;
reg   [2:0] in_buf_id_4_load_1_ce_reg_149;
reg   [2:0] in_buf_id_3_load_ce_reg_159;
reg   [31:0] in_buf_data_4_load_1_ce_reg_169;
reg   [31:0] in_buf_data_3_load_ce_reg_179;
wire   [31:0] in_buf_data_3_load_load_fu_189_p1;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] in_buf_data_4_load_load_fu_192_p1;
wire   [2:0] in_buf_id_3_load_load_fu_195_p1;
wire   [2:0] in_buf_id_4_load_load_fu_198_p1;
reg   [0:0] tmp_4_reg_339;
wire    ap_loop_init;
reg   [31:0] in_buf_data_3_load_23_fu_62;
wire   [31:0] in_buf_data_3_fu_201_p1;
reg   [31:0] in_buf_data_4_load6_fu_66;
reg   [2:0] in_buf_id_3_load_29_fu_70;
reg   [2:0] in_buf_id_4_load12_fu_74;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_block_pp0_stage0_01001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_207;
reg    ap_condition_212;
reg    ap_condition_215;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 in_buf_data_3_load_23_fu_62 = 32'd0;
#0 in_buf_data_4_load6_fu_66 = 32'd0;
#0 in_buf_id_3_load_29_fu_70 = 3'd0;
#0 in_buf_id_4_load12_fu_74 = 3'd0;
#0 ap_done_reg = 1'b0;
end

audio_clean_up_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if (((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
            ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_212)) begin
            i_reg_136 <= 1'd1;
        end else if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            i_reg_136 <= 1'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((tmp_4_nbreadreq_fu_94_p3 == 1'd0) & (ap_start_int == 1'b1))) begin
            in_buf_data_3_load_ce_reg_179 <= in_buf_data_3_load_load_fu_189_p1;
        end else if ((1'b1 == ap_condition_215)) begin
            in_buf_data_3_load_ce_reg_179 <= in_buf_data_3_load_23_fu_62;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((tmp_4_nbreadreq_fu_94_p3 == 1'd0) & (ap_start_int == 1'b1))) begin
            in_buf_data_4_load_1_ce_reg_169 <= in_buf_data_4_load_load_fu_192_p1;
        end else if ((1'b1 == ap_condition_215)) begin
            in_buf_data_4_load_1_ce_reg_169 <= in_buf_data_4_load6_fu_66;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((tmp_4_nbreadreq_fu_94_p3 == 1'd0) & (ap_start_int == 1'b1))) begin
            in_buf_id_3_load_ce_reg_159 <= in_buf_id_3_load_load_fu_195_p1;
        end else if ((1'b1 == ap_condition_215)) begin
            in_buf_id_3_load_ce_reg_159 <= in_buf_id_3_load_29_fu_70;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((tmp_4_nbreadreq_fu_94_p3 == 1'd0) & (ap_start_int == 1'b1))) begin
            in_buf_id_4_load_1_ce_reg_149 <= in_buf_id_4_load_load_fu_198_p1;
        end else if ((1'b1 == ap_condition_215)) begin
            in_buf_id_4_load_1_ce_reg_149 <= in_buf_id_4_load12_fu_74;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_140_p4 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_4_nbreadreq_fu_94_p3 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_buf_data_3_load_23_fu_62 <= in_buf_data_3_fu_201_p1;
        in_buf_id_3_load_29_fu_70 <= {{in_stream_dout[34:32]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_140_p4 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_4_nbreadreq_fu_94_p3 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_buf_data_4_load6_fu_66 <= in_buf_data_3_fu_201_p1;
        in_buf_id_4_load12_fu_74 <= {{in_stream_dout[34:32]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_4_reg_339 <= tmp_4_nbreadreq_fu_94_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((ap_phi_mux_i_phi_fu_140_p4 == 1'd1) | (tmp_4_nbreadreq_fu_94_p3 == 1'd0)))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_207)) begin
            ap_phi_mux_i_phi_fu_140_p4 = 1'd1;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_i_phi_fu_140_p4 = 1'd0;
        end else begin
            ap_phi_mux_i_phi_fu_140_p4 = i_reg_136;
        end
    end else begin
        ap_phi_mux_i_phi_fu_140_p4 = i_reg_136;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & ((tmp_4_reg_339 == 1'd0) | (i_reg_136 == 1'd1)))) begin
        in_buf_data_3_load_ce_out_ap_vld = 1'b1;
    end else begin
        in_buf_data_3_load_ce_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & ((tmp_4_reg_339 == 1'd0) | (i_reg_136 == 1'd1)))) begin
        in_buf_data_4_load_1_ce_out_ap_vld = 1'b1;
    end else begin
        in_buf_data_4_load_1_ce_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & ((tmp_4_reg_339 == 1'd0) | (i_reg_136 == 1'd1)))) begin
        in_buf_id_3_load_ce_out_ap_vld = 1'b1;
    end else begin
        in_buf_id_3_load_ce_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & ((tmp_4_reg_339 == 1'd0) | (i_reg_136 == 1'd1)))) begin
        in_buf_id_4_load_1_ce_out_ap_vld = 1'b1;
    end else begin
        in_buf_id_4_load_1_ce_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (tmp_4_nbreadreq_fu_94_p3 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_blk_n = in_stream_empty_n;
    end else begin
        in_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_4_nbreadreq_fu_94_p3 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_read = 1'b1;
    end else begin
        in_stream_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((tmp_4_nbreadreq_fu_94_p3 == 1'd1) & (in_stream_empty_n == 1'b0));
end

always @ (*) begin
    ap_condition_207 = ((tmp_4_reg_339 == 1'd1) & (i_reg_136 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_212 = ((tmp_4_reg_339 == 1'd1) & (i_reg_136 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_215 = ((tmp_4_reg_339 == 1'd1) & (i_reg_136 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign in_buf_data_3_fu_201_p1 = in_stream_dout[31:0];

assign in_buf_data_3_load_ce_out = in_buf_data_3_load_ce_reg_179;

assign in_buf_data_3_load_load_fu_189_p1 = in_buf_data_3_load_23_fu_62;

assign in_buf_data_4_load_1_ce_out = in_buf_data_4_load_1_ce_reg_169;

assign in_buf_data_4_load_load_fu_192_p1 = in_buf_data_4_load6_fu_66;

assign in_buf_id_3_load_ce_out = in_buf_id_3_load_ce_reg_159;

assign in_buf_id_3_load_load_fu_195_p1 = in_buf_id_3_load_29_fu_70;

assign in_buf_id_4_load_1_ce_out = in_buf_id_4_load_1_ce_reg_149;

assign in_buf_id_4_load_load_fu_198_p1 = in_buf_id_4_load12_fu_74;

assign tmp_4_nbreadreq_fu_94_p3 = in_stream_empty_n;

endmodule //audio_clean_up_dc_cut_Pipeline_READ_LOOP
