-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity audio_clean_up_dc_cut is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_stream_dout : IN STD_LOGIC_VECTOR (34 downto 0);
    in_stream_empty_n : IN STD_LOGIC;
    in_stream_read : OUT STD_LOGIC;
    mid_stream_din : OUT STD_LOGIC_VECTOR (34 downto 0);
    mid_stream_full_n : IN STD_LOGIC;
    mid_stream_write : OUT STD_LOGIC;
    a_coef : IN STD_LOGIC_VECTOR (31 downto 0);
    dc_pass : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of audio_clean_up_dc_cut is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv34_0 : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv54_0 : STD_LOGIC_VECTOR (53 downto 0) := "000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv63_0 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv12_433 : STD_LOGIC_VECTOR (11 downto 0) := "010000110011";
    constant ap_const_lv12_16 : STD_LOGIC_VECTOR (11 downto 0) := "000000010110";
    constant ap_const_lv11_7EA : STD_LOGIC_VECTOR (10 downto 0) := "11111101010";
    constant ap_const_lv11_16 : STD_LOGIC_VECTOR (10 downto 0) := "00000010110";
    constant ap_const_lv11_36 : STD_LOGIC_VECTOR (10 downto 0) := "00000110110";
    constant ap_const_lv24_FFFFFF : STD_LOGIC_VECTOR (23 downto 0) := "111111111111111111111111";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv11_18 : STD_LOGIC_VECTOR (10 downto 0) := "00000011000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal inited_1 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal st_x1L : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000000000000000000000000";
    signal st_y1L : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000000000000000000000000";
    signal st_x1R : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000000000000000000000000";
    signal st_y1R : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000000000000000000000000";
    signal dc_pass_read_read_fu_180_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln104_fu_448_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal trunc_ln104_reg_895 : STD_LOGIC_VECTOR (62 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_reg_900 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_reg_906 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln104_1_fu_468_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal trunc_ln104_1_reg_911 : STD_LOGIC_VECTOR (51 downto 0);
    signal select_ln104_fu_492_p3 : STD_LOGIC_VECTOR (53 downto 0);
    signal select_ln104_reg_916 : STD_LOGIC_VECTOR (53 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln104_fu_499_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln104_reg_921 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln104_1_fu_514_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln104_1_reg_928 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln104_1_fu_532_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln104_1_reg_933 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln104_2_fu_540_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln104_2_reg_941 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln104_3_fu_546_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln104_3_reg_947 : STD_LOGIC_VECTOR (23 downto 0);
    signal select_ln104_2_fu_574_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal select_ln104_2_reg_953 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal select_ln104_3_fu_595_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal select_ln104_3_reg_958 : STD_LOGIC_VECTOR (23 downto 0);
    signal a_fu_637_p11 : STD_LOGIC_VECTOR (23 downto 0);
    signal a_reg_963 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_dc_cut_Pipeline_READ_LOOP_fu_345_ap_start : STD_LOGIC;
    signal grp_dc_cut_Pipeline_READ_LOOP_fu_345_ap_done : STD_LOGIC;
    signal grp_dc_cut_Pipeline_READ_LOOP_fu_345_ap_idle : STD_LOGIC;
    signal grp_dc_cut_Pipeline_READ_LOOP_fu_345_ap_ready : STD_LOGIC;
    signal grp_dc_cut_Pipeline_READ_LOOP_fu_345_in_stream_read : STD_LOGIC;
    signal grp_dc_cut_Pipeline_READ_LOOP_fu_345_in_buf_id_4_load_1_ce_out : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dc_cut_Pipeline_READ_LOOP_fu_345_in_buf_id_4_load_1_ce_out_ap_vld : STD_LOGIC;
    signal grp_dc_cut_Pipeline_READ_LOOP_fu_345_in_buf_id_3_load_ce_out : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dc_cut_Pipeline_READ_LOOP_fu_345_in_buf_id_3_load_ce_out_ap_vld : STD_LOGIC;
    signal grp_dc_cut_Pipeline_READ_LOOP_fu_345_in_buf_data_4_load_1_ce_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dc_cut_Pipeline_READ_LOOP_fu_345_in_buf_data_4_load_1_ce_out_ap_vld : STD_LOGIC;
    signal grp_dc_cut_Pipeline_READ_LOOP_fu_345_in_buf_data_3_load_ce_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dc_cut_Pipeline_READ_LOOP_fu_345_in_buf_data_3_load_ce_out_ap_vld : STD_LOGIC;
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_ap_start : STD_LOGIC;
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_ap_done : STD_LOGIC;
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_ap_idle : STD_LOGIC;
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_ap_ready : STD_LOGIC;
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_data : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_data_ap_vld : STD_LOGIC;
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_id : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_id_ap_vld : STD_LOGIC;
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_data_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_data_2_ap_vld : STD_LOGIC;
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_id_2 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_id_2_ap_vld : STD_LOGIC;
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_id_2_load29_out : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_id_2_load29_out_ap_vld : STD_LOGIC;
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_id_load24_out : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_id_load24_out_ap_vld : STD_LOGIC;
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_data_2_load19_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_data_2_load19_out_ap_vld : STD_LOGIC;
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_data_load14_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_data_load14_out_ap_vld : STD_LOGIC;
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_x1L_1_out : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_x1L_1_out_ap_vld : STD_LOGIC;
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_y1L_1_out : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_y1L_1_out_ap_vld : STD_LOGIC;
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_x1R_1_out : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_x1R_1_out_ap_vld : STD_LOGIC;
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_y1R_1_out : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_y1R_1_out_ap_vld : STD_LOGIC;
    signal grp_dc_cut_Pipeline_PASS_LOOP_fu_384_ap_start : STD_LOGIC;
    signal grp_dc_cut_Pipeline_PASS_LOOP_fu_384_ap_done : STD_LOGIC;
    signal grp_dc_cut_Pipeline_PASS_LOOP_fu_384_ap_idle : STD_LOGIC;
    signal grp_dc_cut_Pipeline_PASS_LOOP_fu_384_ap_ready : STD_LOGIC;
    signal grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_data : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_data_ap_vld : STD_LOGIC;
    signal grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_id : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_id_ap_vld : STD_LOGIC;
    signal grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_data_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_data_2_ap_vld : STD_LOGIC;
    signal grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_id_2 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_id_2_ap_vld : STD_LOGIC;
    signal grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_id_2_load32_out : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_id_2_load32_out_ap_vld : STD_LOGIC;
    signal grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_id_load27_out : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_id_load27_out_ap_vld : STD_LOGIC;
    signal grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_data_2_load22_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_data_2_load22_out_ap_vld : STD_LOGIC;
    signal grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_data_load17_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_data_load17_out_ap_vld : STD_LOGIC;
    signal grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_ap_start : STD_LOGIC;
    signal grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_ap_done : STD_LOGIC;
    signal grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_ap_idle : STD_LOGIC;
    signal grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_ap_ready : STD_LOGIC;
    signal grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_mid_stream_din : STD_LOGIC_VECTOR (34 downto 0);
    signal grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_mid_stream_write : STD_LOGIC;
    signal st_x1L_flag_0_reg_192 : STD_LOGIC_VECTOR (0 downto 0);
    signal inited_1_load_load_fu_418_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal x1L_reg_206 : STD_LOGIC_VECTOR (33 downto 0);
    signal y1L_reg_218 : STD_LOGIC_VECTOR (33 downto 0);
    signal x1R_reg_230 : STD_LOGIC_VECTOR (33 downto 0);
    signal y1R_reg_242 : STD_LOGIC_VECTOR (33 downto 0);
    signal ap_phi_mux_st_x1L_flag_1_phi_fu_257_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_phi_mux_st_x1L_new_1_phi_fu_268_p4 : STD_LOGIC_VECTOR (33 downto 0);
    signal ap_phi_mux_st_y1L_new_1_phi_fu_278_p4 : STD_LOGIC_VECTOR (33 downto 0);
    signal ap_phi_mux_st_x1R_new_1_phi_fu_288_p4 : STD_LOGIC_VECTOR (33 downto 0);
    signal ap_phi_mux_st_y1R_new_1_phi_fu_298_p4 : STD_LOGIC_VECTOR (33 downto 0);
    signal out_buf_id_2_load_reg_305 : STD_LOGIC_VECTOR (2 downto 0);
    signal out_buf_id_load_reg_315 : STD_LOGIC_VECTOR (2 downto 0);
    signal out_buf_data_2_load_reg_325 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_buf_data_load_reg_335 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dc_cut_Pipeline_READ_LOOP_fu_345_ap_start_reg : STD_LOGIC := '0';
    signal grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_dc_cut_Pipeline_PASS_LOOP_fu_384_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal grp_fu_414_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln716_fu_444_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln104_1_cast_fu_475_p3 : STD_LOGIC_VECTOR (52 downto 0);
    signal zext_ln104_1_fu_482_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal sub_ln104_fu_486_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal zext_ln104_fu_472_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln104_1_fu_504_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln104_2_fu_510_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln104_fu_520_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln104_2_fu_526_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln104_2_fu_562_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal ashr_ln104_fu_565_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal icmp_ln104_3_fu_550_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln104_4_fu_570_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal select_ln104_4_fu_555_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal select_ln104_1cast_fu_587_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal icmp_ln104_4_fu_582_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln104_fu_590_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal xor_ln104_fu_603_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln104_fu_613_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln104_1_fu_617_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln104_fu_608_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln104_1_fu_623_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal a_fu_637_p9 : STD_LOGIC_VECTOR (23 downto 0);
    signal a_fu_637_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_fu_414_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal a_fu_637_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal a_fu_637_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal a_fu_637_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal a_fu_637_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component audio_clean_up_dc_cut_Pipeline_READ_LOOP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_stream_dout : IN STD_LOGIC_VECTOR (34 downto 0);
        in_stream_empty_n : IN STD_LOGIC;
        in_stream_read : OUT STD_LOGIC;
        in_buf_id_4_load_1_ce_out : OUT STD_LOGIC_VECTOR (2 downto 0);
        in_buf_id_4_load_1_ce_out_ap_vld : OUT STD_LOGIC;
        in_buf_id_3_load_ce_out : OUT STD_LOGIC_VECTOR (2 downto 0);
        in_buf_id_3_load_ce_out_ap_vld : OUT STD_LOGIC;
        in_buf_data_4_load_1_ce_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        in_buf_data_4_load_1_ce_out_ap_vld : OUT STD_LOGIC;
        in_buf_data_3_load_ce_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        in_buf_data_3_load_ce_out_ap_vld : OUT STD_LOGIC );
    end component;


    component audio_clean_up_dc_cut_Pipeline_MAIN_LOOP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        x1L : IN STD_LOGIC_VECTOR (33 downto 0);
        y1L : IN STD_LOGIC_VECTOR (33 downto 0);
        x1R : IN STD_LOGIC_VECTOR (33 downto 0);
        y1R : IN STD_LOGIC_VECTOR (33 downto 0);
        out_buf_data : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_buf_data_ap_vld : OUT STD_LOGIC;
        out_buf_id : OUT STD_LOGIC_VECTOR (2 downto 0);
        out_buf_id_ap_vld : OUT STD_LOGIC;
        in_buf_data_4_load_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_buf_data_3_load : IN STD_LOGIC_VECTOR (31 downto 0);
        in_buf_id_4_load_1 : IN STD_LOGIC_VECTOR (2 downto 0);
        in_buf_id_3_load : IN STD_LOGIC_VECTOR (2 downto 0);
        sext_ln37 : IN STD_LOGIC_VECTOR (23 downto 0);
        out_buf_data_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_buf_data_2_ap_vld : OUT STD_LOGIC;
        out_buf_id_2 : OUT STD_LOGIC_VECTOR (2 downto 0);
        out_buf_id_2_ap_vld : OUT STD_LOGIC;
        out_buf_id_2_load29_out : OUT STD_LOGIC_VECTOR (2 downto 0);
        out_buf_id_2_load29_out_ap_vld : OUT STD_LOGIC;
        out_buf_id_load24_out : OUT STD_LOGIC_VECTOR (2 downto 0);
        out_buf_id_load24_out_ap_vld : OUT STD_LOGIC;
        out_buf_data_2_load19_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_buf_data_2_load19_out_ap_vld : OUT STD_LOGIC;
        out_buf_data_load14_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_buf_data_load14_out_ap_vld : OUT STD_LOGIC;
        x1L_1_out : OUT STD_LOGIC_VECTOR (33 downto 0);
        x1L_1_out_ap_vld : OUT STD_LOGIC;
        y1L_1_out : OUT STD_LOGIC_VECTOR (33 downto 0);
        y1L_1_out_ap_vld : OUT STD_LOGIC;
        x1R_1_out : OUT STD_LOGIC_VECTOR (33 downto 0);
        x1R_1_out_ap_vld : OUT STD_LOGIC;
        y1R_1_out : OUT STD_LOGIC_VECTOR (33 downto 0);
        y1R_1_out_ap_vld : OUT STD_LOGIC );
    end component;


    component audio_clean_up_dc_cut_Pipeline_PASS_LOOP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        out_buf_data : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_buf_data_ap_vld : OUT STD_LOGIC;
        out_buf_id : OUT STD_LOGIC_VECTOR (2 downto 0);
        out_buf_id_ap_vld : OUT STD_LOGIC;
        in_buf_data_4_load_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_buf_data_3_load : IN STD_LOGIC_VECTOR (31 downto 0);
        in_buf_id_4_load_1 : IN STD_LOGIC_VECTOR (2 downto 0);
        in_buf_id_3_load : IN STD_LOGIC_VECTOR (2 downto 0);
        out_buf_data_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_buf_data_2_ap_vld : OUT STD_LOGIC;
        out_buf_id_2 : OUT STD_LOGIC_VECTOR (2 downto 0);
        out_buf_id_2_ap_vld : OUT STD_LOGIC;
        out_buf_id_2_load32_out : OUT STD_LOGIC_VECTOR (2 downto 0);
        out_buf_id_2_load32_out_ap_vld : OUT STD_LOGIC;
        out_buf_id_load27_out : OUT STD_LOGIC_VECTOR (2 downto 0);
        out_buf_id_load27_out_ap_vld : OUT STD_LOGIC;
        out_buf_data_2_load22_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_buf_data_2_load22_out_ap_vld : OUT STD_LOGIC;
        out_buf_data_load17_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_buf_data_load17_out_ap_vld : OUT STD_LOGIC );
    end component;


    component audio_clean_up_dc_cut_Pipeline_WRITE_LOOP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        mid_stream_din : OUT STD_LOGIC_VECTOR (34 downto 0);
        mid_stream_full_n : IN STD_LOGIC;
        mid_stream_write : OUT STD_LOGIC;
        out_buf_data_2_load : IN STD_LOGIC_VECTOR (31 downto 0);
        out_buf_data_load : IN STD_LOGIC_VECTOR (31 downto 0);
        out_buf_id_2_load : IN STD_LOGIC_VECTOR (2 downto 0);
        out_buf_id_load : IN STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component audio_clean_up_fpext_32ns_64_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component audio_clean_up_sparsemux_9_3_24_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (23 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        din2 : IN STD_LOGIC_VECTOR (23 downto 0);
        din3 : IN STD_LOGIC_VECTOR (23 downto 0);
        def : IN STD_LOGIC_VECTOR (23 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;



begin
    grp_dc_cut_Pipeline_READ_LOOP_fu_345 : component audio_clean_up_dc_cut_Pipeline_READ_LOOP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dc_cut_Pipeline_READ_LOOP_fu_345_ap_start,
        ap_done => grp_dc_cut_Pipeline_READ_LOOP_fu_345_ap_done,
        ap_idle => grp_dc_cut_Pipeline_READ_LOOP_fu_345_ap_idle,
        ap_ready => grp_dc_cut_Pipeline_READ_LOOP_fu_345_ap_ready,
        in_stream_dout => in_stream_dout,
        in_stream_empty_n => in_stream_empty_n,
        in_stream_read => grp_dc_cut_Pipeline_READ_LOOP_fu_345_in_stream_read,
        in_buf_id_4_load_1_ce_out => grp_dc_cut_Pipeline_READ_LOOP_fu_345_in_buf_id_4_load_1_ce_out,
        in_buf_id_4_load_1_ce_out_ap_vld => grp_dc_cut_Pipeline_READ_LOOP_fu_345_in_buf_id_4_load_1_ce_out_ap_vld,
        in_buf_id_3_load_ce_out => grp_dc_cut_Pipeline_READ_LOOP_fu_345_in_buf_id_3_load_ce_out,
        in_buf_id_3_load_ce_out_ap_vld => grp_dc_cut_Pipeline_READ_LOOP_fu_345_in_buf_id_3_load_ce_out_ap_vld,
        in_buf_data_4_load_1_ce_out => grp_dc_cut_Pipeline_READ_LOOP_fu_345_in_buf_data_4_load_1_ce_out,
        in_buf_data_4_load_1_ce_out_ap_vld => grp_dc_cut_Pipeline_READ_LOOP_fu_345_in_buf_data_4_load_1_ce_out_ap_vld,
        in_buf_data_3_load_ce_out => grp_dc_cut_Pipeline_READ_LOOP_fu_345_in_buf_data_3_load_ce_out,
        in_buf_data_3_load_ce_out_ap_vld => grp_dc_cut_Pipeline_READ_LOOP_fu_345_in_buf_data_3_load_ce_out_ap_vld);

    grp_dc_cut_Pipeline_MAIN_LOOP_fu_355 : component audio_clean_up_dc_cut_Pipeline_MAIN_LOOP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_ap_start,
        ap_done => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_ap_done,
        ap_idle => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_ap_idle,
        ap_ready => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_ap_ready,
        x1L => x1L_reg_206,
        y1L => y1L_reg_218,
        x1R => x1R_reg_230,
        y1R => y1R_reg_242,
        out_buf_data => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_data,
        out_buf_data_ap_vld => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_data_ap_vld,
        out_buf_id => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_id,
        out_buf_id_ap_vld => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_id_ap_vld,
        in_buf_data_4_load_1 => grp_dc_cut_Pipeline_READ_LOOP_fu_345_in_buf_data_4_load_1_ce_out,
        in_buf_data_3_load => grp_dc_cut_Pipeline_READ_LOOP_fu_345_in_buf_data_3_load_ce_out,
        in_buf_id_4_load_1 => grp_dc_cut_Pipeline_READ_LOOP_fu_345_in_buf_id_4_load_1_ce_out,
        in_buf_id_3_load => grp_dc_cut_Pipeline_READ_LOOP_fu_345_in_buf_id_3_load_ce_out,
        sext_ln37 => a_reg_963,
        out_buf_data_2 => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_data_2,
        out_buf_data_2_ap_vld => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_data_2_ap_vld,
        out_buf_id_2 => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_id_2,
        out_buf_id_2_ap_vld => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_id_2_ap_vld,
        out_buf_id_2_load29_out => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_id_2_load29_out,
        out_buf_id_2_load29_out_ap_vld => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_id_2_load29_out_ap_vld,
        out_buf_id_load24_out => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_id_load24_out,
        out_buf_id_load24_out_ap_vld => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_id_load24_out_ap_vld,
        out_buf_data_2_load19_out => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_data_2_load19_out,
        out_buf_data_2_load19_out_ap_vld => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_data_2_load19_out_ap_vld,
        out_buf_data_load14_out => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_data_load14_out,
        out_buf_data_load14_out_ap_vld => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_data_load14_out_ap_vld,
        x1L_1_out => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_x1L_1_out,
        x1L_1_out_ap_vld => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_x1L_1_out_ap_vld,
        y1L_1_out => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_y1L_1_out,
        y1L_1_out_ap_vld => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_y1L_1_out_ap_vld,
        x1R_1_out => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_x1R_1_out,
        x1R_1_out_ap_vld => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_x1R_1_out_ap_vld,
        y1R_1_out => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_y1R_1_out,
        y1R_1_out_ap_vld => grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_y1R_1_out_ap_vld);

    grp_dc_cut_Pipeline_PASS_LOOP_fu_384 : component audio_clean_up_dc_cut_Pipeline_PASS_LOOP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dc_cut_Pipeline_PASS_LOOP_fu_384_ap_start,
        ap_done => grp_dc_cut_Pipeline_PASS_LOOP_fu_384_ap_done,
        ap_idle => grp_dc_cut_Pipeline_PASS_LOOP_fu_384_ap_idle,
        ap_ready => grp_dc_cut_Pipeline_PASS_LOOP_fu_384_ap_ready,
        out_buf_data => grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_data,
        out_buf_data_ap_vld => grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_data_ap_vld,
        out_buf_id => grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_id,
        out_buf_id_ap_vld => grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_id_ap_vld,
        in_buf_data_4_load_1 => grp_dc_cut_Pipeline_READ_LOOP_fu_345_in_buf_data_4_load_1_ce_out,
        in_buf_data_3_load => grp_dc_cut_Pipeline_READ_LOOP_fu_345_in_buf_data_3_load_ce_out,
        in_buf_id_4_load_1 => grp_dc_cut_Pipeline_READ_LOOP_fu_345_in_buf_id_4_load_1_ce_out,
        in_buf_id_3_load => grp_dc_cut_Pipeline_READ_LOOP_fu_345_in_buf_id_3_load_ce_out,
        out_buf_data_2 => grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_data_2,
        out_buf_data_2_ap_vld => grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_data_2_ap_vld,
        out_buf_id_2 => grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_id_2,
        out_buf_id_2_ap_vld => grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_id_2_ap_vld,
        out_buf_id_2_load32_out => grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_id_2_load32_out,
        out_buf_id_2_load32_out_ap_vld => grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_id_2_load32_out_ap_vld,
        out_buf_id_load27_out => grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_id_load27_out,
        out_buf_id_load27_out_ap_vld => grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_id_load27_out_ap_vld,
        out_buf_data_2_load22_out => grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_data_2_load22_out,
        out_buf_data_2_load22_out_ap_vld => grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_data_2_load22_out_ap_vld,
        out_buf_data_load17_out => grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_data_load17_out,
        out_buf_data_load17_out_ap_vld => grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_data_load17_out_ap_vld);

    grp_dc_cut_Pipeline_WRITE_LOOP_fu_400 : component audio_clean_up_dc_cut_Pipeline_WRITE_LOOP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_ap_start,
        ap_done => grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_ap_done,
        ap_idle => grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_ap_idle,
        ap_ready => grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_ap_ready,
        mid_stream_din => grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_mid_stream_din,
        mid_stream_full_n => mid_stream_full_n,
        mid_stream_write => grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_mid_stream_write,
        out_buf_data_2_load => out_buf_data_2_load_reg_325,
        out_buf_data_load => out_buf_data_load_reg_335,
        out_buf_id_2_load => out_buf_id_2_load_reg_305,
        out_buf_id_load => out_buf_id_load_reg_315);

    fpext_32ns_64_2_no_dsp_1_U52 : component audio_clean_up_fpext_32ns_64_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => a_coef,
        ce => grp_fu_414_ce,
        dout => grp_fu_414_p1);

    sparsemux_9_3_24_1_1_U53 : component audio_clean_up_sparsemux_9_3_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100",
        din0_WIDTH => 24,
        CASE1 => "010",
        din1_WIDTH => 24,
        CASE2 => "001",
        din2_WIDTH => 24,
        CASE3 => "000",
        din3_WIDTH => 24,
        def_WIDTH => 24,
        sel_WIDTH => 3,
        dout_WIDTH => 24)
    port map (
        din0 => ap_const_lv24_0,
        din1 => trunc_ln104_3_reg_947,
        din2 => select_ln104_2_reg_953,
        din3 => select_ln104_3_reg_958,
        def => a_fu_637_p9,
        sel => a_fu_637_p10,
        dout => a_fu_637_p11);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_ap_start_reg <= ap_const_logic_0;
            else
                if (((dc_pass_read_read_fu_180_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_ap_ready = ap_const_logic_1)) then 
                    grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_dc_cut_Pipeline_PASS_LOOP_fu_384_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dc_cut_Pipeline_PASS_LOOP_fu_384_ap_start_reg <= ap_const_logic_0;
            else
                if (((dc_pass_read_read_fu_180_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    grp_dc_cut_Pipeline_PASS_LOOP_fu_384_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dc_cut_Pipeline_PASS_LOOP_fu_384_ap_ready = ap_const_logic_1)) then 
                    grp_dc_cut_Pipeline_PASS_LOOP_fu_384_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_dc_cut_Pipeline_READ_LOOP_fu_345_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dc_cut_Pipeline_READ_LOOP_fu_345_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_dc_cut_Pipeline_READ_LOOP_fu_345_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dc_cut_Pipeline_READ_LOOP_fu_345_ap_ready = ap_const_logic_1)) then 
                    grp_dc_cut_Pipeline_READ_LOOP_fu_345_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_ap_ready = ap_const_logic_1)) then 
                    grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    out_buf_data_2_load_reg_325_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                if ((dc_pass_read_read_fu_180_p2 = ap_const_lv1_0)) then 
                    out_buf_data_2_load_reg_325 <= grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_data_2_load19_out;
                elsif ((dc_pass_read_read_fu_180_p2 = ap_const_lv1_1)) then 
                    out_buf_data_2_load_reg_325 <= grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_data_2_load22_out;
                end if;
            end if; 
        end if;
    end process;

    out_buf_data_load_reg_335_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                if ((dc_pass_read_read_fu_180_p2 = ap_const_lv1_0)) then 
                    out_buf_data_load_reg_335 <= grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_data_load14_out;
                elsif ((dc_pass_read_read_fu_180_p2 = ap_const_lv1_1)) then 
                    out_buf_data_load_reg_335 <= grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_data_load17_out;
                end if;
            end if; 
        end if;
    end process;

    out_buf_id_2_load_reg_305_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                if ((dc_pass_read_read_fu_180_p2 = ap_const_lv1_0)) then 
                    out_buf_id_2_load_reg_305 <= grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_id_2_load29_out;
                elsif ((dc_pass_read_read_fu_180_p2 = ap_const_lv1_1)) then 
                    out_buf_id_2_load_reg_305 <= grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_id_2_load32_out;
                end if;
            end if; 
        end if;
    end process;

    out_buf_id_load_reg_315_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                if ((dc_pass_read_read_fu_180_p2 = ap_const_lv1_0)) then 
                    out_buf_id_load_reg_315 <= grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_out_buf_id_load24_out;
                elsif ((dc_pass_read_read_fu_180_p2 = ap_const_lv1_1)) then 
                    out_buf_id_load_reg_315 <= grp_dc_cut_Pipeline_PASS_LOOP_fu_384_out_buf_id_load27_out;
                end if;
            end if; 
        end if;
    end process;

    st_x1L_flag_0_reg_192_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                if ((inited_1_load_load_fu_418_p1 = ap_const_lv1_0)) then 
                    st_x1L_flag_0_reg_192 <= ap_const_lv1_1;
                elsif ((inited_1_load_load_fu_418_p1 = ap_const_lv1_1)) then 
                    st_x1L_flag_0_reg_192 <= ap_const_lv1_0;
                end if;
            end if; 
        end if;
    end process;

    x1L_reg_206_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                if ((inited_1_load_load_fu_418_p1 = ap_const_lv1_0)) then 
                    x1L_reg_206 <= ap_const_lv34_0;
                elsif ((inited_1_load_load_fu_418_p1 = ap_const_lv1_1)) then 
                    x1L_reg_206 <= st_x1L;
                end if;
            end if; 
        end if;
    end process;

    x1R_reg_230_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                if ((inited_1_load_load_fu_418_p1 = ap_const_lv1_0)) then 
                    x1R_reg_230 <= ap_const_lv34_0;
                elsif ((inited_1_load_load_fu_418_p1 = ap_const_lv1_1)) then 
                    x1R_reg_230 <= st_x1R;
                end if;
            end if; 
        end if;
    end process;

    y1L_reg_218_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                if ((inited_1_load_load_fu_418_p1 = ap_const_lv1_0)) then 
                    y1L_reg_218 <= ap_const_lv34_0;
                elsif ((inited_1_load_load_fu_418_p1 = ap_const_lv1_1)) then 
                    y1L_reg_218 <= st_y1L;
                end if;
            end if; 
        end if;
    end process;

    y1R_reg_242_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                if ((inited_1_load_load_fu_418_p1 = ap_const_lv1_0)) then 
                    y1R_reg_242 <= ap_const_lv34_0;
                elsif ((inited_1_load_load_fu_418_p1 = ap_const_lv1_1)) then 
                    y1R_reg_242 <= st_y1R;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                a_reg_963 <= a_fu_637_p11;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                icmp_ln104_1_reg_928 <= icmp_ln104_1_fu_514_p2;
                icmp_ln104_2_reg_941 <= icmp_ln104_2_fu_540_p2;
                icmp_ln104_reg_921 <= icmp_ln104_fu_499_p2;
                select_ln104_1_reg_933 <= select_ln104_1_fu_532_p3;
                select_ln104_reg_916 <= select_ln104_fu_492_p3;
                trunc_ln104_3_reg_947 <= trunc_ln104_3_fu_546_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (inited_1_load_load_fu_418_p1 = ap_const_lv1_0) and (ap_start = ap_const_logic_1))) then
                inited_1 <= ap_const_lv1_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                select_ln104_2_reg_953 <= select_ln104_2_fu_574_p3;
                select_ln104_3_reg_958 <= select_ln104_3_fu_595_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_phi_mux_st_x1L_flag_1_phi_fu_257_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                st_x1L <= ap_phi_mux_st_x1L_new_1_phi_fu_268_p4;
                st_x1R <= ap_phi_mux_st_x1R_new_1_phi_fu_288_p4;
                st_y1L <= ap_phi_mux_st_y1L_new_1_phi_fu_278_p4;
                st_y1R <= ap_phi_mux_st_y1R_new_1_phi_fu_298_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                tmp_1_reg_906 <= bitcast_ln716_fu_444_p1(62 downto 52);
                tmp_reg_900 <= bitcast_ln716_fu_444_p1(63 downto 63);
                trunc_ln104_1_reg_911 <= trunc_ln104_1_fu_468_p1;
                trunc_ln104_reg_895 <= trunc_ln104_fu_448_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, dc_pass_read_read_fu_180_p2, ap_CS_fsm_state2, ap_CS_fsm_state5, grp_dc_cut_Pipeline_READ_LOOP_fu_345_ap_done, grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_ap_done, grp_dc_cut_Pipeline_PASS_LOOP_fu_384_ap_done, grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_ap_done, ap_CS_fsm_state6, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_dc_cut_Pipeline_READ_LOOP_fu_345_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((dc_pass_read_read_fu_180_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_dc_cut_Pipeline_PASS_LOOP_fu_384_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    a_fu_637_p10 <= ((icmp_ln104_reg_921 & and_ln104_fu_608_p2) & and_ln104_1_fu_623_p2);
    a_fu_637_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXX";
    add_ln104_fu_520_p2 <= std_logic_vector(unsigned(trunc_ln104_2_fu_510_p1) + unsigned(ap_const_lv11_7EA));
    and_ln104_1_fu_623_p2 <= (xor_ln104_1_fu_617_p2 and icmp_ln104_1_reg_928);
    and_ln104_fu_608_p2 <= (xor_ln104_fu_603_p2 and icmp_ln104_2_reg_941);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_dc_cut_Pipeline_READ_LOOP_fu_345_ap_done)
    begin
        if ((grp_dc_cut_Pipeline_READ_LOOP_fu_345_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_ap_done)
    begin
        if ((grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_dc_cut_Pipeline_PASS_LOOP_fu_384_ap_done)
    begin
        if ((grp_dc_cut_Pipeline_PASS_LOOP_fu_384_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state9_blk_assign_proc : process(grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_ap_done)
    begin
        if ((grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_ap_done, ap_CS_fsm_state9)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_ap_done = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_st_x1L_flag_1_phi_fu_257_p4_assign_proc : process(dc_pass_read_read_fu_180_p2, st_x1L_flag_0_reg_192, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
            if ((dc_pass_read_read_fu_180_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_st_x1L_flag_1_phi_fu_257_p4 <= ap_const_lv1_1;
            elsif ((dc_pass_read_read_fu_180_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_st_x1L_flag_1_phi_fu_257_p4 <= st_x1L_flag_0_reg_192;
            else 
                ap_phi_mux_st_x1L_flag_1_phi_fu_257_p4 <= "X";
            end if;
        else 
            ap_phi_mux_st_x1L_flag_1_phi_fu_257_p4 <= "X";
        end if; 
    end process;


    ap_phi_mux_st_x1L_new_1_phi_fu_268_p4_assign_proc : process(dc_pass_read_read_fu_180_p2, grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_x1L_1_out, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
            if ((dc_pass_read_read_fu_180_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_st_x1L_new_1_phi_fu_268_p4 <= grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_x1L_1_out;
            elsif ((dc_pass_read_read_fu_180_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_st_x1L_new_1_phi_fu_268_p4 <= ap_const_lv34_0;
            else 
                ap_phi_mux_st_x1L_new_1_phi_fu_268_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_st_x1L_new_1_phi_fu_268_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_st_x1R_new_1_phi_fu_288_p4_assign_proc : process(dc_pass_read_read_fu_180_p2, grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_x1R_1_out, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
            if ((dc_pass_read_read_fu_180_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_st_x1R_new_1_phi_fu_288_p4 <= grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_x1R_1_out;
            elsif ((dc_pass_read_read_fu_180_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_st_x1R_new_1_phi_fu_288_p4 <= ap_const_lv34_0;
            else 
                ap_phi_mux_st_x1R_new_1_phi_fu_288_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_st_x1R_new_1_phi_fu_288_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_st_y1L_new_1_phi_fu_278_p4_assign_proc : process(dc_pass_read_read_fu_180_p2, grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_y1L_1_out, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
            if ((dc_pass_read_read_fu_180_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_st_y1L_new_1_phi_fu_278_p4 <= grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_y1L_1_out;
            elsif ((dc_pass_read_read_fu_180_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_st_y1L_new_1_phi_fu_278_p4 <= ap_const_lv34_0;
            else 
                ap_phi_mux_st_y1L_new_1_phi_fu_278_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_st_y1L_new_1_phi_fu_278_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_st_y1R_new_1_phi_fu_298_p4_assign_proc : process(dc_pass_read_read_fu_180_p2, grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_y1R_1_out, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
            if ((dc_pass_read_read_fu_180_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_st_y1R_new_1_phi_fu_298_p4 <= grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_y1R_1_out;
            elsif ((dc_pass_read_read_fu_180_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_st_y1R_new_1_phi_fu_298_p4 <= ap_const_lv34_0;
            else 
                ap_phi_mux_st_y1R_new_1_phi_fu_298_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_st_y1R_new_1_phi_fu_298_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_ap_done, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_ap_done = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ashr_ln104_fu_565_p2 <= std_logic_vector(shift_right(signed(select_ln104_reg_916),to_integer(unsigned('0' & zext_ln104_2_fu_562_p1(31-1 downto 0)))));
    bitcast_ln716_fu_444_p1 <= grp_fu_414_p1;
    dc_pass_read_read_fu_180_p2 <= dc_pass;
    grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_ap_start <= grp_dc_cut_Pipeline_MAIN_LOOP_fu_355_ap_start_reg;
    grp_dc_cut_Pipeline_PASS_LOOP_fu_384_ap_start <= grp_dc_cut_Pipeline_PASS_LOOP_fu_384_ap_start_reg;
    grp_dc_cut_Pipeline_READ_LOOP_fu_345_ap_start <= grp_dc_cut_Pipeline_READ_LOOP_fu_345_ap_start_reg;
    grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_ap_start <= grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_ap_start_reg;

    grp_fu_414_ce_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, grp_dc_cut_Pipeline_READ_LOOP_fu_345_ap_done)
    begin
        if ((((grp_dc_cut_Pipeline_READ_LOOP_fu_345_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            grp_fu_414_ce <= ap_const_logic_1;
        else 
            grp_fu_414_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln104_1_fu_514_p2 <= "1" when (signed(sub_ln104_1_fu_504_p2) > signed(ap_const_lv12_16)) else "0";
    icmp_ln104_2_fu_540_p2 <= "1" when (sub_ln104_1_fu_504_p2 = ap_const_lv12_16) else "0";
    icmp_ln104_3_fu_550_p2 <= "1" when (unsigned(select_ln104_1_reg_933) < unsigned(ap_const_lv11_36)) else "0";
    icmp_ln104_4_fu_582_p2 <= "1" when (unsigned(select_ln104_1_reg_933) < unsigned(ap_const_lv11_18)) else "0";
    icmp_ln104_fu_499_p2 <= "1" when (trunc_ln104_reg_895 = ap_const_lv63_0) else "0";
    in_stream_read <= grp_dc_cut_Pipeline_READ_LOOP_fu_345_in_stream_read;
    inited_1_load_load_fu_418_p1 <= inited_1;
    mid_stream_din <= grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_mid_stream_din;
    mid_stream_write <= grp_dc_cut_Pipeline_WRITE_LOOP_fu_400_mid_stream_write;
    or_ln104_fu_613_p2 <= (icmp_ln104_reg_921 or icmp_ln104_2_reg_941);
    select_ln104_1_fu_532_p3 <= 
        add_ln104_fu_520_p2 when (icmp_ln104_1_fu_514_p2(0) = '1') else 
        sub_ln104_2_fu_526_p2;
    select_ln104_1cast_fu_587_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln104_1_reg_933),24));
    select_ln104_2_fu_574_p3 <= 
        trunc_ln104_4_fu_570_p1 when (icmp_ln104_3_fu_550_p2(0) = '1') else 
        select_ln104_4_fu_555_p3;
    select_ln104_3_fu_595_p3 <= 
        shl_ln104_fu_590_p2 when (icmp_ln104_4_fu_582_p2(0) = '1') else 
        ap_const_lv24_0;
    select_ln104_4_fu_555_p3 <= 
        ap_const_lv24_FFFFFF when (tmp_reg_900(0) = '1') else 
        ap_const_lv24_0;
    select_ln104_fu_492_p3 <= 
        sub_ln104_fu_486_p2 when (tmp_reg_900(0) = '1') else 
        zext_ln104_1_fu_482_p1;
    shl_ln104_fu_590_p2 <= std_logic_vector(shift_left(unsigned(trunc_ln104_3_reg_947),to_integer(unsigned('0' & select_ln104_1cast_fu_587_p1(24-1 downto 0)))));
    sub_ln104_1_fu_504_p2 <= std_logic_vector(unsigned(ap_const_lv12_433) - unsigned(zext_ln104_fu_472_p1));
    sub_ln104_2_fu_526_p2 <= std_logic_vector(unsigned(ap_const_lv11_16) - unsigned(trunc_ln104_2_fu_510_p1));
    sub_ln104_fu_486_p2 <= std_logic_vector(unsigned(ap_const_lv54_0) - unsigned(zext_ln104_1_fu_482_p1));
    trunc_ln104_1_fu_468_p1 <= bitcast_ln716_fu_444_p1(52 - 1 downto 0);
    trunc_ln104_2_fu_510_p1 <= sub_ln104_1_fu_504_p2(11 - 1 downto 0);
    trunc_ln104_3_fu_546_p1 <= select_ln104_fu_492_p3(24 - 1 downto 0);
    trunc_ln104_4_fu_570_p1 <= ashr_ln104_fu_565_p2(24 - 1 downto 0);
    trunc_ln104_fu_448_p1 <= bitcast_ln716_fu_444_p1(63 - 1 downto 0);
    xor_ln104_1_fu_617_p2 <= (or_ln104_fu_613_p2 xor ap_const_lv1_1);
    xor_ln104_fu_603_p2 <= (icmp_ln104_reg_921 xor ap_const_lv1_1);
    zext_ln104_1_cast_fu_475_p3 <= (ap_const_lv1_1 & trunc_ln104_1_reg_911);
    zext_ln104_1_fu_482_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln104_1_cast_fu_475_p3),54));
    zext_ln104_2_fu_562_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln104_1_reg_933),54));
    zext_ln104_fu_472_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_reg_906),12));
end behav;
