-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity audio_clean_up is
generic (
    C_S_AXI_ACU_ADDR_WIDTH : INTEGER := 7;
    C_S_AXI_ACU_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_axis_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    s_axis_TVALID : IN STD_LOGIC;
    s_axis_TREADY : OUT STD_LOGIC;
    s_axis_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    s_axis_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    s_axis_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_TID : IN STD_LOGIC_VECTOR (2 downto 0);
    m_axis_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axis_TVALID : OUT STD_LOGIC;
    m_axis_TREADY : IN STD_LOGIC;
    m_axis_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_TID : OUT STD_LOGIC_VECTOR (2 downto 0);
    s_axi_acu_AWVALID : IN STD_LOGIC;
    s_axi_acu_AWREADY : OUT STD_LOGIC;
    s_axi_acu_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ACU_ADDR_WIDTH-1 downto 0);
    s_axi_acu_WVALID : IN STD_LOGIC;
    s_axi_acu_WREADY : OUT STD_LOGIC;
    s_axi_acu_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_ACU_DATA_WIDTH-1 downto 0);
    s_axi_acu_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_ACU_DATA_WIDTH/8-1 downto 0);
    s_axi_acu_ARVALID : IN STD_LOGIC;
    s_axi_acu_ARREADY : OUT STD_LOGIC;
    s_axi_acu_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ACU_ADDR_WIDTH-1 downto 0);
    s_axi_acu_RVALID : OUT STD_LOGIC;
    s_axi_acu_RREADY : IN STD_LOGIC;
    s_axi_acu_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_ACU_DATA_WIDTH-1 downto 0);
    s_axi_acu_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_acu_BVALID : OUT STD_LOGIC;
    s_axi_acu_BREADY : IN STD_LOGIC;
    s_axi_acu_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of audio_clean_up is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "audio_clean_up_audio_clean_up,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.234000,HLS_SYN_LAT=62,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=3445,HLS_SYN_LUT=4520,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (13 downto 0) := "00000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (13 downto 0) := "00000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (13 downto 0) := "00000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (13 downto 0) := "00000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (13 downto 0) := "00000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (13 downto 0) := "00000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (13 downto 0) := "00001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (13 downto 0) := "00010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (13 downto 0) := "00100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (13 downto 0) := "01000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (13 downto 0) := "10000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal dc_a_coef : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_pass : STD_LOGIC_VECTOR (0 downto 0);
    signal th_open_amp : STD_LOGIC_VECTOR (33 downto 0);
    signal th_close_amp : STD_LOGIC_VECTOR (33 downto 0);
    signal a_attack : STD_LOGIC_VECTOR (23 downto 0);
    signal a_release : STD_LOGIC_VECTOR (23 downto 0);
    signal b_attack : STD_LOGIC_VECTOR (23 downto 0);
    signal b_release : STD_LOGIC_VECTOR (23 downto 0);
    signal ng_pass : STD_LOGIC_VECTOR (0 downto 0);
    signal inited : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal st_gainL : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal st_gainR : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal st_gate_openL : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal st_gate_openR : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal st_th_open_amp : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000000000000000000000000";
    signal st_th_close_amp : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000000000000000000000000";
    signal st_a_attack : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal st_a_release : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal st_b_attack : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal st_b_release : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_5 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_4 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal ng_pass_read_reg_469 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal b_release_read_reg_474 : STD_LOGIC_VECTOR (23 downto 0);
    signal b_attack_read_reg_479 : STD_LOGIC_VECTOR (23 downto 0);
    signal a_release_read_reg_484 : STD_LOGIC_VECTOR (23 downto 0);
    signal a_attack_read_reg_489 : STD_LOGIC_VECTOR (23 downto 0);
    signal th_close_amp_read_reg_494 : STD_LOGIC_VECTOR (33 downto 0);
    signal th_open_amp_read_reg_499 : STD_LOGIC_VECTOR (33 downto 0);
    signal dc_pass_read_reg_504 : STD_LOGIC_VECTOR (0 downto 0);
    signal dc_a_coef_read_reg_509 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_ap_start : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_ap_done : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_ap_idle : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_ap_ready : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_in_stream_din : STD_LOGIC_VECTOR (34 downto 0);
    signal grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_in_stream_write : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_s_axis_TREADY : STD_LOGIC;
    signal grp_dc_cut_fu_269_ap_start : STD_LOGIC;
    signal grp_dc_cut_fu_269_ap_done : STD_LOGIC;
    signal grp_dc_cut_fu_269_ap_idle : STD_LOGIC;
    signal grp_dc_cut_fu_269_ap_ready : STD_LOGIC;
    signal grp_dc_cut_fu_269_in_stream_read : STD_LOGIC;
    signal grp_dc_cut_fu_269_mid_stream_din : STD_LOGIC_VECTOR (34 downto 0);
    signal grp_dc_cut_fu_269_mid_stream_write : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_ap_start : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_ap_done : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_ap_idle : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_ap_ready : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_mid_stream_read : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_7 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_7_ap_vld : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_5 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_5_ap_vld : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_6 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_6_ap_vld : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_4 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_4_ap_vld : STD_LOGIC;
    signal grp_core_fu_302_ap_start : STD_LOGIC;
    signal grp_core_fu_302_ap_done : STD_LOGIC;
    signal grp_core_fu_302_ap_idle : STD_LOGIC;
    signal grp_core_fu_302_ap_ready : STD_LOGIC;
    signal grp_core_fu_302_st_gainL_o : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_core_fu_302_st_gainL_o_ap_vld : STD_LOGIC;
    signal grp_core_fu_302_st_gainR_o : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_core_fu_302_st_gainR_o_ap_vld : STD_LOGIC;
    signal grp_core_fu_302_st_gate_openL_o : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_core_fu_302_st_gate_openL_o_ap_vld : STD_LOGIC;
    signal grp_core_fu_302_st_gate_openR_o : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_core_fu_302_st_gate_openR_o_ap_vld : STD_LOGIC;
    signal grp_core_fu_302_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_core_fu_302_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld : STD_LOGIC;
    signal grp_core_fu_302_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_core_fu_302_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld : STD_LOGIC;
    signal grp_core_fu_302_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_core_fu_302_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld : STD_LOGIC;
    signal grp_core_fu_302_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_core_fu_302_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343_ap_start : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343_ap_done : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343_ap_idle : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343_ap_ready : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343_out_stream_din : STD_LOGIC_VECTOR (34 downto 0);
    signal grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343_out_stream_write : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_ap_start : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_ap_done : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_ap_idle : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_ap_ready : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_out_stream_read : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TREADY : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TVALID : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TID : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal in_stream_full_n : STD_LOGIC;
    signal in_stream_write : STD_LOGIC;
    signal grp_dc_cut_fu_269_ap_start_reg : STD_LOGIC := '0';
    signal in_stream_dout : STD_LOGIC_VECTOR (34 downto 0);
    signal in_stream_empty_n : STD_LOGIC;
    signal in_stream_read : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal mid_stream_full_n : STD_LOGIC;
    signal mid_stream_write : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal mid_stream_dout : STD_LOGIC_VECTOR (34 downto 0);
    signal mid_stream_empty_n : STD_LOGIC;
    signal mid_stream_read : STD_LOGIC;
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_core_fu_302_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal out_stream_full_n : STD_LOGIC;
    signal out_stream_write : STD_LOGIC;
    signal grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal out_stream_dout : STD_LOGIC_VECTOR (34 downto 0);
    signal out_stream_empty_n : STD_LOGIC;
    signal out_stream_read : STD_LOGIC;
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal m_axis_TDATA_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal m_axis_TKEEP_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal m_axis_TSTRB_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal m_axis_TLAST_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_TID_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal inited_load_load_fu_367_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal regslice_both_m_axis_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal regslice_both_s_axis_V_data_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal s_axis_TVALID_int_regslice : STD_LOGIC;
    signal s_axis_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_s_axis_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_s_axis_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_s_axis_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_V_last_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_s_axis_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_V_id_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_TID_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_s_axis_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_V_id_V_U_ack_in : STD_LOGIC;
    signal m_axis_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal m_axis_TVALID_int_regslice : STD_LOGIC;
    signal m_axis_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_m_axis_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal m_axis_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_m_axis_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal m_axis_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_m_axis_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_V_last_V_U_apdone_blk : STD_LOGIC;
    signal m_axis_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_m_axis_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_V_id_V_U_apdone_blk : STD_LOGIC;
    signal m_axis_TID_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_m_axis_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_V_id_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component audio_clean_up_audio_clean_up_Pipeline_READ_FROM_PORT IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_axis_TVALID : IN STD_LOGIC;
        in_stream_din : OUT STD_LOGIC_VECTOR (34 downto 0);
        in_stream_full_n : IN STD_LOGIC;
        in_stream_write : OUT STD_LOGIC;
        s_axis_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        s_axis_TREADY : OUT STD_LOGIC;
        s_axis_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        s_axis_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        s_axis_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_TID : IN STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component audio_clean_up_dc_cut IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_stream_dout : IN STD_LOGIC_VECTOR (34 downto 0);
        in_stream_empty_n : IN STD_LOGIC;
        in_stream_read : OUT STD_LOGIC;
        mid_stream_din : OUT STD_LOGIC_VECTOR (34 downto 0);
        mid_stream_full_n : IN STD_LOGIC;
        mid_stream_write : OUT STD_LOGIC;
        a_coef : IN STD_LOGIC_VECTOR (31 downto 0);
        dc_pass : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component audio_clean_up_audio_clean_up_Pipeline_READ_LOOP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        mid_stream_dout : IN STD_LOGIC_VECTOR (34 downto 0);
        mid_stream_empty_n : IN STD_LOGIC;
        mid_stream_read : OUT STD_LOGIC;
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_7 : OUT STD_LOGIC_VECTOR (31 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_7_ap_vld : OUT STD_LOGIC;
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_5 : OUT STD_LOGIC_VECTOR (2 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_5_ap_vld : OUT STD_LOGIC;
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_6 : OUT STD_LOGIC_VECTOR (31 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_6_ap_vld : OUT STD_LOGIC;
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_4 : OUT STD_LOGIC_VECTOR (2 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_4_ap_vld : OUT STD_LOGIC );
    end component;


    component audio_clean_up_core IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ng_pass : IN STD_LOGIC_VECTOR (0 downto 0);
        st_gainL_i : IN STD_LOGIC_VECTOR (23 downto 0);
        st_gainL_o : OUT STD_LOGIC_VECTOR (23 downto 0);
        st_gainL_o_ap_vld : OUT STD_LOGIC;
        st_gainR_i : IN STD_LOGIC_VECTOR (23 downto 0);
        st_gainR_o : OUT STD_LOGIC_VECTOR (23 downto 0);
        st_gainR_o_ap_vld : OUT STD_LOGIC;
        st_gate_openL_i : IN STD_LOGIC_VECTOR (0 downto 0);
        st_gate_openL_o : OUT STD_LOGIC_VECTOR (0 downto 0);
        st_gate_openL_o_ap_vld : OUT STD_LOGIC;
        st_gate_openR_i : IN STD_LOGIC_VECTOR (0 downto 0);
        st_gate_openR_o : OUT STD_LOGIC_VECTOR (0 downto 0);
        st_gate_openR_o_ap_vld : OUT STD_LOGIC;
        st_th_open_amp : IN STD_LOGIC_VECTOR (33 downto 0);
        st_th_close_amp : IN STD_LOGIC_VECTOR (33 downto 0);
        st_a_attack : IN STD_LOGIC_VECTOR (23 downto 0);
        st_a_release : IN STD_LOGIC_VECTOR (23 downto 0);
        st_b_attack : IN STD_LOGIC_VECTOR (23 downto 0);
        st_b_release : IN STD_LOGIC_VECTOR (23 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_7 : IN STD_LOGIC_VECTOR (31 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_6 : IN STD_LOGIC_VECTOR (31 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_5 : IN STD_LOGIC_VECTOR (2 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_4 : IN STD_LOGIC_VECTOR (2 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld : OUT STD_LOGIC;
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld : OUT STD_LOGIC;
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld : OUT STD_LOGIC;
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed : OUT STD_LOGIC_VECTOR (2 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld : OUT STD_LOGIC );
    end component;


    component audio_clean_up_audio_clean_up_Pipeline_WRITE_LOOP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        out_stream_din : OUT STD_LOGIC_VECTOR (34 downto 0);
        out_stream_full_n : IN STD_LOGIC;
        out_stream_write : OUT STD_LOGIC;
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_13 : IN STD_LOGIC_VECTOR (31 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_12 : IN STD_LOGIC_VECTOR (31 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_15 : IN STD_LOGIC_VECTOR (2 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_14 : IN STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component audio_clean_up_audio_clean_up_Pipeline_WRITE_TO_PORT IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        out_stream_dout : IN STD_LOGIC_VECTOR (34 downto 0);
        out_stream_empty_n : IN STD_LOGIC;
        out_stream_read : OUT STD_LOGIC;
        m_axis_TREADY : IN STD_LOGIC;
        m_axis_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axis_TVALID : OUT STD_LOGIC;
        m_axis_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axis_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axis_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axis_TID : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component audio_clean_up_fifo_w35_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (34 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (34 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component audio_clean_up_acu_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        dc_a_coef : OUT STD_LOGIC_VECTOR (31 downto 0);
        dc_pass : OUT STD_LOGIC_VECTOR (0 downto 0);
        th_open_amp : OUT STD_LOGIC_VECTOR (33 downto 0);
        th_close_amp : OUT STD_LOGIC_VECTOR (33 downto 0);
        a_attack : OUT STD_LOGIC_VECTOR (23 downto 0);
        a_release : OUT STD_LOGIC_VECTOR (23 downto 0);
        b_attack : OUT STD_LOGIC_VECTOR (23 downto 0);
        b_release : OUT STD_LOGIC_VECTOR (23 downto 0);
        ng_pass : OUT STD_LOGIC_VECTOR (0 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component audio_clean_up_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254 : component audio_clean_up_audio_clean_up_Pipeline_READ_FROM_PORT
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_ap_start,
        ap_done => grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_ap_done,
        ap_idle => grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_ap_idle,
        ap_ready => grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_ap_ready,
        s_axis_TVALID => s_axis_TVALID_int_regslice,
        in_stream_din => grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_in_stream_din,
        in_stream_full_n => in_stream_full_n,
        in_stream_write => grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_in_stream_write,
        s_axis_TDATA => s_axis_TDATA_int_regslice,
        s_axis_TREADY => grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_s_axis_TREADY,
        s_axis_TKEEP => s_axis_TKEEP_int_regslice,
        s_axis_TSTRB => s_axis_TSTRB_int_regslice,
        s_axis_TLAST => s_axis_TLAST_int_regslice,
        s_axis_TID => s_axis_TID_int_regslice);

    grp_dc_cut_fu_269 : component audio_clean_up_dc_cut
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_dc_cut_fu_269_ap_start,
        ap_done => grp_dc_cut_fu_269_ap_done,
        ap_idle => grp_dc_cut_fu_269_ap_idle,
        ap_ready => grp_dc_cut_fu_269_ap_ready,
        in_stream_dout => in_stream_dout,
        in_stream_empty_n => in_stream_empty_n,
        in_stream_read => grp_dc_cut_fu_269_in_stream_read,
        mid_stream_din => grp_dc_cut_fu_269_mid_stream_din,
        mid_stream_full_n => mid_stream_full_n,
        mid_stream_write => grp_dc_cut_fu_269_mid_stream_write,
        a_coef => dc_a_coef_read_reg_509,
        dc_pass => dc_pass_read_reg_504);

    grp_audio_clean_up_Pipeline_READ_LOOP_fu_289 : component audio_clean_up_audio_clean_up_Pipeline_READ_LOOP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_ap_start,
        ap_done => grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_ap_done,
        ap_idle => grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_ap_idle,
        ap_ready => grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_ap_ready,
        mid_stream_dout => mid_stream_dout,
        mid_stream_empty_n => mid_stream_empty_n,
        mid_stream_read => grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_mid_stream_read,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_7 => grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_7,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_7_ap_vld => grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_7_ap_vld,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_5 => grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_5,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_5_ap_vld => grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_5_ap_vld,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_6 => grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_6,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_6_ap_vld => grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_6_ap_vld,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_4 => grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_4,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_4_ap_vld => grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_4_ap_vld);

    grp_core_fu_302 : component audio_clean_up_core
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_core_fu_302_ap_start,
        ap_done => grp_core_fu_302_ap_done,
        ap_idle => grp_core_fu_302_ap_idle,
        ap_ready => grp_core_fu_302_ap_ready,
        ng_pass => ng_pass_read_reg_469,
        st_gainL_i => st_gainL,
        st_gainL_o => grp_core_fu_302_st_gainL_o,
        st_gainL_o_ap_vld => grp_core_fu_302_st_gainL_o_ap_vld,
        st_gainR_i => st_gainR,
        st_gainR_o => grp_core_fu_302_st_gainR_o,
        st_gainR_o_ap_vld => grp_core_fu_302_st_gainR_o_ap_vld,
        st_gate_openL_i => st_gate_openL,
        st_gate_openL_o => grp_core_fu_302_st_gate_openL_o,
        st_gate_openL_o_ap_vld => grp_core_fu_302_st_gate_openL_o_ap_vld,
        st_gate_openR_i => st_gate_openR,
        st_gate_openR_o => grp_core_fu_302_st_gate_openR_o,
        st_gate_openR_o_ap_vld => grp_core_fu_302_st_gate_openR_o_ap_vld,
        st_th_open_amp => st_th_open_amp,
        st_th_close_amp => st_th_close_amp,
        st_a_attack => st_a_attack,
        st_a_release => st_a_release,
        st_b_attack => st_b_attack,
        st_b_release => st_b_release,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_7 => noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_7,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_6 => noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_6,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_5 => noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_5,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_4 => noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_4,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3 => grp_core_fu_302_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld => grp_core_fu_302_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1 => grp_core_fu_302_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld => grp_core_fu_302_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2 => grp_core_fu_302_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld => grp_core_fu_302_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed => grp_core_fu_302_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld => grp_core_fu_302_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld);

    grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343 : component audio_clean_up_audio_clean_up_Pipeline_WRITE_LOOP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343_ap_start,
        ap_done => grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343_ap_done,
        ap_idle => grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343_ap_idle,
        ap_ready => grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343_ap_ready,
        out_stream_din => grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343_out_stream_din,
        out_stream_full_n => out_stream_full_n,
        out_stream_write => grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343_out_stream_write,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_13 => noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_12 => noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_15 => noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_14 => noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1);

    grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352 : component audio_clean_up_audio_clean_up_Pipeline_WRITE_TO_PORT
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_ap_start,
        ap_done => grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_ap_done,
        ap_idle => grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_ap_idle,
        ap_ready => grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_ap_ready,
        out_stream_dout => out_stream_dout,
        out_stream_empty_n => out_stream_empty_n,
        out_stream_read => grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_out_stream_read,
        m_axis_TREADY => grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TREADY,
        m_axis_TDATA => grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TDATA,
        m_axis_TVALID => grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TVALID,
        m_axis_TKEEP => grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TKEEP,
        m_axis_TSTRB => grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TSTRB,
        m_axis_TLAST => grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TLAST,
        m_axis_TID => grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TID);

    acu_s_axi_U : component audio_clean_up_acu_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_ACU_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_ACU_DATA_WIDTH)
    port map (
        AWVALID => s_axi_acu_AWVALID,
        AWREADY => s_axi_acu_AWREADY,
        AWADDR => s_axi_acu_AWADDR,
        WVALID => s_axi_acu_WVALID,
        WREADY => s_axi_acu_WREADY,
        WDATA => s_axi_acu_WDATA,
        WSTRB => s_axi_acu_WSTRB,
        ARVALID => s_axi_acu_ARVALID,
        ARREADY => s_axi_acu_ARREADY,
        ARADDR => s_axi_acu_ARADDR,
        RVALID => s_axi_acu_RVALID,
        RREADY => s_axi_acu_RREADY,
        RDATA => s_axi_acu_RDATA,
        RRESP => s_axi_acu_RRESP,
        BVALID => s_axi_acu_BVALID,
        BREADY => s_axi_acu_BREADY,
        BRESP => s_axi_acu_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        dc_a_coef => dc_a_coef,
        dc_pass => dc_pass,
        th_open_amp => th_open_amp,
        th_close_amp => th_close_amp,
        a_attack => a_attack,
        a_release => a_release,
        b_attack => b_attack,
        b_release => b_release,
        ng_pass => ng_pass,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    in_stream_fifo_U : component audio_clean_up_fifo_w35_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_in_stream_din,
        if_full_n => in_stream_full_n,
        if_write => in_stream_write,
        if_dout => in_stream_dout,
        if_empty_n => in_stream_empty_n,
        if_read => in_stream_read);

    mid_stream_fifo_U : component audio_clean_up_fifo_w35_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => grp_dc_cut_fu_269_mid_stream_din,
        if_full_n => mid_stream_full_n,
        if_write => mid_stream_write,
        if_dout => mid_stream_dout,
        if_empty_n => mid_stream_empty_n,
        if_read => mid_stream_read);

    out_stream_fifo_U : component audio_clean_up_fifo_w35_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343_out_stream_din,
        if_full_n => out_stream_full_n,
        if_write => out_stream_write,
        if_dout => out_stream_dout,
        if_empty_n => out_stream_empty_n,
        if_read => out_stream_read);

    regslice_both_s_axis_V_data_V_U : component audio_clean_up_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_TDATA,
        vld_in => s_axis_TVALID,
        ack_in => regslice_both_s_axis_V_data_V_U_ack_in,
        data_out => s_axis_TDATA_int_regslice,
        vld_out => s_axis_TVALID_int_regslice,
        ack_out => s_axis_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_V_data_V_U_apdone_blk);

    regslice_both_s_axis_V_keep_V_U : component audio_clean_up_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_TKEEP,
        vld_in => s_axis_TVALID,
        ack_in => regslice_both_s_axis_V_keep_V_U_ack_in,
        data_out => s_axis_TKEEP_int_regslice,
        vld_out => regslice_both_s_axis_V_keep_V_U_vld_out,
        ack_out => s_axis_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_V_keep_V_U_apdone_blk);

    regslice_both_s_axis_V_strb_V_U : component audio_clean_up_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_TSTRB,
        vld_in => s_axis_TVALID,
        ack_in => regslice_both_s_axis_V_strb_V_U_ack_in,
        data_out => s_axis_TSTRB_int_regslice,
        vld_out => regslice_both_s_axis_V_strb_V_U_vld_out,
        ack_out => s_axis_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_V_strb_V_U_apdone_blk);

    regslice_both_s_axis_V_last_V_U : component audio_clean_up_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_TLAST,
        vld_in => s_axis_TVALID,
        ack_in => regslice_both_s_axis_V_last_V_U_ack_in,
        data_out => s_axis_TLAST_int_regslice,
        vld_out => regslice_both_s_axis_V_last_V_U_vld_out,
        ack_out => s_axis_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_V_last_V_U_apdone_blk);

    regslice_both_s_axis_V_id_V_U : component audio_clean_up_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_TID,
        vld_in => s_axis_TVALID,
        ack_in => regslice_both_s_axis_V_id_V_U_ack_in,
        data_out => s_axis_TID_int_regslice,
        vld_out => regslice_both_s_axis_V_id_V_U_vld_out,
        ack_out => s_axis_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_V_id_V_U_apdone_blk);

    regslice_both_m_axis_V_data_V_U : component audio_clean_up_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => m_axis_TDATA_int_regslice,
        vld_in => grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TVALID,
        ack_in => m_axis_TREADY_int_regslice,
        data_out => m_axis_TDATA,
        vld_out => regslice_both_m_axis_V_data_V_U_vld_out,
        ack_out => m_axis_TREADY,
        apdone_blk => regslice_both_m_axis_V_data_V_U_apdone_blk);

    regslice_both_m_axis_V_keep_V_U : component audio_clean_up_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => m_axis_TKEEP_int_regslice,
        vld_in => grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TVALID,
        ack_in => regslice_both_m_axis_V_keep_V_U_ack_in_dummy,
        data_out => m_axis_TKEEP,
        vld_out => regslice_both_m_axis_V_keep_V_U_vld_out,
        ack_out => m_axis_TREADY,
        apdone_blk => regslice_both_m_axis_V_keep_V_U_apdone_blk);

    regslice_both_m_axis_V_strb_V_U : component audio_clean_up_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => m_axis_TSTRB_int_regslice,
        vld_in => grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TVALID,
        ack_in => regslice_both_m_axis_V_strb_V_U_ack_in_dummy,
        data_out => m_axis_TSTRB,
        vld_out => regslice_both_m_axis_V_strb_V_U_vld_out,
        ack_out => m_axis_TREADY,
        apdone_blk => regslice_both_m_axis_V_strb_V_U_apdone_blk);

    regslice_both_m_axis_V_last_V_U : component audio_clean_up_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => m_axis_TLAST_int_regslice,
        vld_in => grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TVALID,
        ack_in => regslice_both_m_axis_V_last_V_U_ack_in_dummy,
        data_out => m_axis_TLAST,
        vld_out => regslice_both_m_axis_V_last_V_U_vld_out,
        ack_out => m_axis_TREADY,
        apdone_blk => regslice_both_m_axis_V_last_V_U_apdone_blk);

    regslice_both_m_axis_V_id_V_U : component audio_clean_up_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => m_axis_TID_int_regslice,
        vld_in => grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TVALID,
        ack_in => regslice_both_m_axis_V_id_V_U_ack_in_dummy,
        data_out => m_axis_TID,
        vld_out => regslice_both_m_axis_V_id_V_U_vld_out,
        ack_out => m_axis_TREADY,
        apdone_blk => regslice_both_m_axis_V_id_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_ap_ready = ap_const_logic_1)) then 
                    grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_ap_ready = ap_const_logic_1)) then 
                    grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                    grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343_ap_ready = ap_const_logic_1)) then 
                    grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
                    grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_ap_ready = ap_const_logic_1)) then 
                    grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_core_fu_302_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_core_fu_302_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    grp_core_fu_302_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_core_fu_302_ap_ready = ap_const_logic_1)) then 
                    grp_core_fu_302_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_dc_cut_fu_269_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_dc_cut_fu_269_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_dc_cut_fu_269_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dc_cut_fu_269_ap_ready = ap_const_logic_1)) then 
                    grp_dc_cut_fu_269_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    st_gainL_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((inited_load_load_fu_367_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5) and (grp_dc_cut_fu_269_ap_done = ap_const_logic_1))) then 
                st_gainL <= ap_const_lv24_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_core_fu_302_st_gainL_o_ap_vld = ap_const_logic_1))) then 
                st_gainL <= grp_core_fu_302_st_gainL_o;
            end if; 
        end if;
    end process;

    st_gainR_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((inited_load_load_fu_367_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5) and (grp_dc_cut_fu_269_ap_done = ap_const_logic_1))) then 
                st_gainR <= ap_const_lv24_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_core_fu_302_st_gainR_o_ap_vld = ap_const_logic_1))) then 
                st_gainR <= grp_core_fu_302_st_gainR_o;
            end if; 
        end if;
    end process;

    st_gate_openL_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((inited_load_load_fu_367_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5) and (grp_dc_cut_fu_269_ap_done = ap_const_logic_1))) then 
                st_gate_openL <= ap_const_lv1_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_core_fu_302_st_gate_openL_o_ap_vld = ap_const_logic_1))) then 
                st_gate_openL <= grp_core_fu_302_st_gate_openL_o;
            end if; 
        end if;
    end process;

    st_gate_openR_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((inited_load_load_fu_367_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5) and (grp_dc_cut_fu_269_ap_done = ap_const_logic_1))) then 
                st_gate_openR <= ap_const_lv1_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_core_fu_302_st_gate_openR_o_ap_vld = ap_const_logic_1))) then 
                st_gate_openR <= grp_core_fu_302_st_gate_openR_o;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                a_attack_read_reg_489 <= a_attack;
                a_release_read_reg_484 <= a_release;
                b_attack_read_reg_479 <= b_attack;
                b_release_read_reg_474 <= b_release;
                dc_a_coef_read_reg_509 <= dc_a_coef;
                dc_pass_read_reg_504 <= dc_pass;
                ng_pass_read_reg_469 <= ng_pass;
                th_close_amp_read_reg_494 <= th_close_amp;
                th_open_amp_read_reg_499 <= th_open_amp;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((inited_load_load_fu_367_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5) and (grp_dc_cut_fu_269_ap_done = ap_const_logic_1))) then
                inited <= ap_const_lv1_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                m_axis_TDATA_reg <= grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TDATA;
                m_axis_TID_reg <= grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TID;
                m_axis_TKEEP_reg <= grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TKEEP;
                m_axis_TLAST_reg <= grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TLAST;
                m_axis_TSTRB_reg <= grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TSTRB;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_core_fu_302_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld = ap_const_logic_1))) then
                noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed <= grp_core_fu_302_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_core_fu_302_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld = ap_const_logic_1))) then
                noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1 <= grp_core_fu_302_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_core_fu_302_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld = ap_const_logic_1))) then
                noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2 <= grp_core_fu_302_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_core_fu_302_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld = ap_const_logic_1))) then
                noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3 <= grp_core_fu_302_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_4_ap_vld = ap_const_logic_1))) then
                noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_4 <= grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_5_ap_vld = ap_const_logic_1))) then
                noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_5 <= grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_6_ap_vld = ap_const_logic_1))) then
                noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_6 <= grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_7_ap_vld = ap_const_logic_1))) then
                noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_7 <= grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_7;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_dc_cut_fu_269_ap_done = ap_const_logic_1))) then
                st_a_attack <= a_attack_read_reg_489;
                st_a_release <= a_release_read_reg_484;
                st_b_attack <= b_attack_read_reg_479;
                st_b_release <= b_release_read_reg_474;
                st_th_close_amp <= th_close_amp_read_reg_494;
                st_th_open_amp <= th_open_amp_read_reg_499;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_ap_done, grp_dc_cut_fu_269_ap_done, grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_ap_done, grp_core_fu_302_ap_done, grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343_ap_done, grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state9, ap_CS_fsm_state11, ap_CS_fsm_state13, ap_CS_fsm_state14, regslice_both_m_axis_V_data_V_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_dc_cut_fu_269_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_core_fu_302_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state11) and (grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                if (((grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when ap_ST_fsm_state14 => 
                if (((regslice_both_m_axis_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state14))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state14;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;

    ap_ST_fsm_state11_blk_assign_proc : process(grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343_ap_done)
    begin
        if ((grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state11_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state11_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state12_blk <= ap_const_logic_0;

    ap_ST_fsm_state13_blk_assign_proc : process(grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_ap_done)
    begin
        if ((grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state13_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state13_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state14_blk_assign_proc : process(regslice_both_m_axis_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_m_axis_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state14_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state14_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_ap_done)
    begin
        if ((grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_dc_cut_fu_269_ap_done)
    begin
        if ((grp_dc_cut_fu_269_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_ap_done)
    begin
        if ((grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_ST_fsm_state9_blk_assign_proc : process(grp_core_fu_302_ap_done)
    begin
        if ((grp_core_fu_302_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state14, regslice_both_m_axis_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_m_axis_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state14, regslice_both_m_axis_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_m_axis_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_ap_start <= grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_ap_start_reg;
    grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_ap_start <= grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_ap_start_reg;
    grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343_ap_start <= grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343_ap_start_reg;
    grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_ap_start <= grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_ap_start_reg;
    grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TREADY <= (m_axis_TREADY_int_regslice and ap_CS_fsm_state13);
    grp_core_fu_302_ap_start <= grp_core_fu_302_ap_start_reg;
    grp_dc_cut_fu_269_ap_start <= grp_dc_cut_fu_269_ap_start_reg;

    in_stream_read_assign_proc : process(grp_dc_cut_fu_269_in_stream_read, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            in_stream_read <= grp_dc_cut_fu_269_in_stream_read;
        else 
            in_stream_read <= ap_const_logic_0;
        end if; 
    end process;


    in_stream_write_assign_proc : process(grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_in_stream_write, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_stream_write <= grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_in_stream_write;
        else 
            in_stream_write <= ap_const_logic_0;
        end if; 
    end process;

    inited_load_load_fu_367_p1 <= inited;

    m_axis_TDATA_int_regslice_assign_proc : process(grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TDATA, grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TVALID, ap_CS_fsm_state13, m_axis_TDATA_reg)
    begin
        if (((grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            m_axis_TDATA_int_regslice <= grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TDATA;
        else 
            m_axis_TDATA_int_regslice <= m_axis_TDATA_reg;
        end if; 
    end process;


    m_axis_TID_int_regslice_assign_proc : process(grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TVALID, grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TID, ap_CS_fsm_state13, m_axis_TID_reg)
    begin
        if (((grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            m_axis_TID_int_regslice <= grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TID;
        else 
            m_axis_TID_int_regslice <= m_axis_TID_reg;
        end if; 
    end process;


    m_axis_TKEEP_int_regslice_assign_proc : process(grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TVALID, grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TKEEP, ap_CS_fsm_state13, m_axis_TKEEP_reg)
    begin
        if (((grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            m_axis_TKEEP_int_regslice <= grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TKEEP;
        else 
            m_axis_TKEEP_int_regslice <= m_axis_TKEEP_reg;
        end if; 
    end process;


    m_axis_TLAST_int_regslice_assign_proc : process(grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TVALID, grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TLAST, ap_CS_fsm_state13, m_axis_TLAST_reg)
    begin
        if (((grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            m_axis_TLAST_int_regslice <= grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TLAST;
        else 
            m_axis_TLAST_int_regslice <= m_axis_TLAST_reg;
        end if; 
    end process;


    m_axis_TSTRB_int_regslice_assign_proc : process(grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TVALID, grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TSTRB, ap_CS_fsm_state13, m_axis_TSTRB_reg)
    begin
        if (((grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            m_axis_TSTRB_int_regslice <= grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TSTRB;
        else 
            m_axis_TSTRB_int_regslice <= m_axis_TSTRB_reg;
        end if; 
    end process;

    m_axis_TVALID <= regslice_both_m_axis_V_data_V_U_vld_out;
    m_axis_TVALID_int_regslice <= grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_m_axis_TVALID;

    mid_stream_read_assign_proc : process(grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_mid_stream_read, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            mid_stream_read <= grp_audio_clean_up_Pipeline_READ_LOOP_fu_289_mid_stream_read;
        else 
            mid_stream_read <= ap_const_logic_0;
        end if; 
    end process;


    mid_stream_write_assign_proc : process(grp_dc_cut_fu_269_mid_stream_write, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mid_stream_write <= grp_dc_cut_fu_269_mid_stream_write;
        else 
            mid_stream_write <= ap_const_logic_0;
        end if; 
    end process;


    out_stream_read_assign_proc : process(grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_out_stream_read, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            out_stream_read <= grp_audio_clean_up_Pipeline_WRITE_TO_PORT_fu_352_out_stream_read;
        else 
            out_stream_read <= ap_const_logic_0;
        end if; 
    end process;


    out_stream_write_assign_proc : process(grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343_out_stream_write, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            out_stream_write <= grp_audio_clean_up_Pipeline_WRITE_LOOP_fu_343_out_stream_write;
        else 
            out_stream_write <= ap_const_logic_0;
        end if; 
    end process;

    s_axis_TREADY <= regslice_both_s_axis_V_data_V_U_ack_in;

    s_axis_TREADY_int_regslice_assign_proc : process(grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_s_axis_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            s_axis_TREADY_int_regslice <= grp_audio_clean_up_Pipeline_READ_FROM_PORT_fu_254_s_axis_TREADY;
        else 
            s_axis_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

end behav;
