-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity audio_clean_up_core is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ng_pass : IN STD_LOGIC_VECTOR (0 downto 0);
    st_gainL_i : IN STD_LOGIC_VECTOR (23 downto 0);
    st_gainL_o : OUT STD_LOGIC_VECTOR (23 downto 0);
    st_gainL_o_ap_vld : OUT STD_LOGIC;
    st_gainR_i : IN STD_LOGIC_VECTOR (23 downto 0);
    st_gainR_o : OUT STD_LOGIC_VECTOR (23 downto 0);
    st_gainR_o_ap_vld : OUT STD_LOGIC;
    st_gate_openL_i : IN STD_LOGIC_VECTOR (0 downto 0);
    st_gate_openL_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    st_gate_openL_o_ap_vld : OUT STD_LOGIC;
    st_gate_openR_i : IN STD_LOGIC_VECTOR (0 downto 0);
    st_gate_openR_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    st_gate_openR_o_ap_vld : OUT STD_LOGIC;
    st_th_open_amp : IN STD_LOGIC_VECTOR (33 downto 0);
    st_th_close_amp : IN STD_LOGIC_VECTOR (33 downto 0);
    st_a_attack : IN STD_LOGIC_VECTOR (23 downto 0);
    st_a_release : IN STD_LOGIC_VECTOR (23 downto 0);
    st_b_attack : IN STD_LOGIC_VECTOR (23 downto 0);
    st_b_release : IN STD_LOGIC_VECTOR (23 downto 0);
    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_7 : IN STD_LOGIC_VECTOR (31 downto 0);
    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_6 : IN STD_LOGIC_VECTOR (31 downto 0);
    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_5 : IN STD_LOGIC_VECTOR (2 downto 0);
    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_4 : IN STD_LOGIC_VECTOR (2 downto 0);
    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld : OUT STD_LOGIC;
    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld : OUT STD_LOGIC;
    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld : OUT STD_LOGIC;
    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed : OUT STD_LOGIC_VECTOR (2 downto 0);
    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld : OUT STD_LOGIC );
end;


architecture behav of audio_clean_up_core is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ng_pass_read_read_fu_62_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_core_Pipeline_MAIN_LOOP_fu_68_ap_start : STD_LOGIC;
    signal grp_core_Pipeline_MAIN_LOOP_fu_68_ap_done : STD_LOGIC;
    signal grp_core_Pipeline_MAIN_LOOP_fu_68_ap_idle : STD_LOGIC;
    signal grp_core_Pipeline_MAIN_LOOP_fu_68_ap_ready : STD_LOGIC;
    signal grp_core_Pipeline_MAIN_LOOP_fu_68_p_out : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_core_Pipeline_MAIN_LOOP_fu_68_p_out_ap_vld : STD_LOGIC;
    signal grp_core_Pipeline_MAIN_LOOP_fu_68_p_out1 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_core_Pipeline_MAIN_LOOP_fu_68_p_out1_ap_vld : STD_LOGIC;
    signal grp_core_Pipeline_MAIN_LOOP_fu_68_gateL_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_core_Pipeline_MAIN_LOOP_fu_68_gateL_1_out_ap_vld : STD_LOGIC;
    signal grp_core_Pipeline_MAIN_LOOP_fu_68_gateR_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_core_Pipeline_MAIN_LOOP_fu_68_gateR_1_out_ap_vld : STD_LOGIC;
    signal grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld : STD_LOGIC;
    signal grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld : STD_LOGIC;
    signal grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld : STD_LOGIC;
    signal grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld : STD_LOGIC;
    signal grp_core_Pipeline_PASS_LOOP_fu_98_ap_start : STD_LOGIC;
    signal grp_core_Pipeline_PASS_LOOP_fu_98_ap_done : STD_LOGIC;
    signal grp_core_Pipeline_PASS_LOOP_fu_98_ap_idle : STD_LOGIC;
    signal grp_core_Pipeline_PASS_LOOP_fu_98_ap_ready : STD_LOGIC;
    signal grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld : STD_LOGIC;
    signal grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld : STD_LOGIC;
    signal grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld : STD_LOGIC;
    signal grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld : STD_LOGIC;
    signal grp_core_Pipeline_MAIN_LOOP_fu_68_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_core_Pipeline_PASS_LOOP_fu_98_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component audio_clean_up_core_Pipeline_MAIN_LOOP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        gainR : IN STD_LOGIC_VECTOR (23 downto 0);
        gainL : IN STD_LOGIC_VECTOR (23 downto 0);
        gateL : IN STD_LOGIC_VECTOR (0 downto 0);
        gateR : IN STD_LOGIC_VECTOR (0 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_9 : IN STD_LOGIC_VECTOR (31 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_8 : IN STD_LOGIC_VECTOR (31 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_11 : IN STD_LOGIC_VECTOR (2 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_10 : IN STD_LOGIC_VECTOR (2 downto 0);
        th_close_amp : IN STD_LOGIC_VECTOR (33 downto 0);
        th_open_amp : IN STD_LOGIC_VECTOR (33 downto 0);
        a_att : IN STD_LOGIC_VECTOR (23 downto 0);
        a_rel : IN STD_LOGIC_VECTOR (23 downto 0);
        b_att : IN STD_LOGIC_VECTOR (23 downto 0);
        b_rel : IN STD_LOGIC_VECTOR (23 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (23 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        p_out1 : OUT STD_LOGIC_VECTOR (23 downto 0);
        p_out1_ap_vld : OUT STD_LOGIC;
        gateL_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        gateL_1_out_ap_vld : OUT STD_LOGIC;
        gateR_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        gateR_1_out_ap_vld : OUT STD_LOGIC;
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld : OUT STD_LOGIC;
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld : OUT STD_LOGIC;
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld : OUT STD_LOGIC;
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed : OUT STD_LOGIC_VECTOR (2 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld : OUT STD_LOGIC );
    end component;


    component audio_clean_up_core_Pipeline_PASS_LOOP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_9 : IN STD_LOGIC_VECTOR (31 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_8 : IN STD_LOGIC_VECTOR (31 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_11 : IN STD_LOGIC_VECTOR (2 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_10 : IN STD_LOGIC_VECTOR (2 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld : OUT STD_LOGIC;
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1 : OUT STD_LOGIC_VECTOR (2 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld : OUT STD_LOGIC;
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld : OUT STD_LOGIC;
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed : OUT STD_LOGIC_VECTOR (2 downto 0);
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_core_Pipeline_MAIN_LOOP_fu_68 : component audio_clean_up_core_Pipeline_MAIN_LOOP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_core_Pipeline_MAIN_LOOP_fu_68_ap_start,
        ap_done => grp_core_Pipeline_MAIN_LOOP_fu_68_ap_done,
        ap_idle => grp_core_Pipeline_MAIN_LOOP_fu_68_ap_idle,
        ap_ready => grp_core_Pipeline_MAIN_LOOP_fu_68_ap_ready,
        gainR => st_gainR_i,
        gainL => st_gainL_i,
        gateL => st_gate_openL_i,
        gateR => st_gate_openR_i,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_9 => noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_6,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_8 => noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_7,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_11 => noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_4,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_10 => noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_5,
        th_close_amp => st_th_close_amp,
        th_open_amp => st_th_open_amp,
        a_att => st_a_attack,
        a_rel => st_a_release,
        b_att => st_b_attack,
        b_rel => st_b_release,
        p_out => grp_core_Pipeline_MAIN_LOOP_fu_68_p_out,
        p_out_ap_vld => grp_core_Pipeline_MAIN_LOOP_fu_68_p_out_ap_vld,
        p_out1 => grp_core_Pipeline_MAIN_LOOP_fu_68_p_out1,
        p_out1_ap_vld => grp_core_Pipeline_MAIN_LOOP_fu_68_p_out1_ap_vld,
        gateL_1_out => grp_core_Pipeline_MAIN_LOOP_fu_68_gateL_1_out,
        gateL_1_out_ap_vld => grp_core_Pipeline_MAIN_LOOP_fu_68_gateL_1_out_ap_vld,
        gateR_1_out => grp_core_Pipeline_MAIN_LOOP_fu_68_gateR_1_out,
        gateR_1_out_ap_vld => grp_core_Pipeline_MAIN_LOOP_fu_68_gateR_1_out_ap_vld,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3 => grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld => grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1 => grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld => grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2 => grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld => grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed => grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld => grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld);

    grp_core_Pipeline_PASS_LOOP_fu_98 : component audio_clean_up_core_Pipeline_PASS_LOOP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_core_Pipeline_PASS_LOOP_fu_98_ap_start,
        ap_done => grp_core_Pipeline_PASS_LOOP_fu_98_ap_done,
        ap_idle => grp_core_Pipeline_PASS_LOOP_fu_98_ap_idle,
        ap_ready => grp_core_Pipeline_PASS_LOOP_fu_98_ap_ready,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_9 => noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_6,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_8 => noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_7,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_11 => noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_4,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_10 => noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_5,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3 => grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld => grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1 => grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld => grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2 => grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld => grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed => grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed,
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld => grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_core_Pipeline_MAIN_LOOP_fu_68_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_core_Pipeline_MAIN_LOOP_fu_68_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ng_pass_read_read_fu_62_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_core_Pipeline_MAIN_LOOP_fu_68_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_core_Pipeline_MAIN_LOOP_fu_68_ap_ready = ap_const_logic_1)) then 
                    grp_core_Pipeline_MAIN_LOOP_fu_68_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_core_Pipeline_PASS_LOOP_fu_98_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_core_Pipeline_PASS_LOOP_fu_98_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ng_pass_read_read_fu_62_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_core_Pipeline_PASS_LOOP_fu_98_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_core_Pipeline_PASS_LOOP_fu_98_ap_ready = ap_const_logic_1)) then 
                    grp_core_Pipeline_PASS_LOOP_fu_98_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld = ap_const_logic_1))) then 
                noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_reg <= grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1;
            elsif (((grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_reg <= grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1;
            end if; 
        end if;
    end process;

    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld = ap_const_logic_1))) then 
                noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_reg <= grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2;
            elsif (((grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_reg <= grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2;
            end if; 
        end if;
    end process;

    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld = ap_const_logic_1))) then 
                noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_reg <= grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3;
            elsif (((grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_reg <= grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3;
            end if; 
        end if;
    end process;

    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld = ap_const_logic_1))) then 
                noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_reg <= grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed;
            elsif (((grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_reg <= grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ng_pass_read_read_fu_62_p2, grp_core_Pipeline_MAIN_LOOP_fu_68_ap_done, grp_core_Pipeline_PASS_LOOP_fu_98_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ng_pass_read_read_fu_62_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                elsif (((ap_start = ap_const_logic_1) and (ng_pass_read_read_fu_62_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_core_Pipeline_MAIN_LOOP_fu_68_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when ap_ST_fsm_state4 => 
                if (((grp_core_Pipeline_PASS_LOOP_fu_98_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_core_Pipeline_MAIN_LOOP_fu_68_ap_done)
    begin
        if ((grp_core_Pipeline_MAIN_LOOP_fu_68_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_core_Pipeline_PASS_LOOP_fu_98_ap_done)
    begin
        if ((grp_core_Pipeline_PASS_LOOP_fu_98_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_core_Pipeline_MAIN_LOOP_fu_68_ap_start <= grp_core_Pipeline_MAIN_LOOP_fu_68_ap_start_reg;
    grp_core_Pipeline_PASS_LOOP_fu_98_ap_start <= grp_core_Pipeline_PASS_LOOP_fu_98_ap_start_reg;
    ng_pass_read_read_fu_62_p2 <= ng_pass;

    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_assign_proc : process(grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed, grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld, grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed, grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld, ap_CS_fsm_state2, noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_reg, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld = ap_const_logic_1))) then 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed <= grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed;
        elsif (((grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed <= grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed;
        else 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed <= noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_reg;
        end if; 
    end process;


    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_assign_proc : process(grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1, grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld, grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1, grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld, ap_CS_fsm_state2, noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_reg, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld = ap_const_logic_1))) then 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1 <= grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1;
        elsif (((grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1 <= grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1;
        else 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1 <= noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_reg;
        end if; 
    end process;


    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld_assign_proc : process(grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld, grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld <= grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld <= grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld;
        else 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_assign_proc : process(grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2, grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld, grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2, grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld, ap_CS_fsm_state2, noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_reg, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld = ap_const_logic_1))) then 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2 <= grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2;
        elsif (((grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2 <= grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2;
        else 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2 <= noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_reg;
        end if; 
    end process;


    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld_assign_proc : process(grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld, grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld <= grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld <= grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld;
        else 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_assign_proc : process(grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3, grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld, grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3, grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld, ap_CS_fsm_state2, noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_reg, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld = ap_const_logic_1))) then 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3 <= grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3;
        elsif (((grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3 <= grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3;
        else 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3 <= noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_reg;
        end if; 
    end process;


    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld_assign_proc : process(grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld, grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld <= grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld <= grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld;
        else 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld_assign_proc : process(grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld, grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld <= grp_core_Pipeline_PASS_LOOP_fu_98_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld <= grp_core_Pipeline_MAIN_LOOP_fu_68_noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld;
        else 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    st_gainL_o_assign_proc : process(st_gainL_i, ng_pass_read_read_fu_62_p2, grp_core_Pipeline_MAIN_LOOP_fu_68_p_out1, ap_CS_fsm_state3)
    begin
        if (((ng_pass_read_read_fu_62_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            st_gainL_o <= grp_core_Pipeline_MAIN_LOOP_fu_68_p_out1;
        else 
            st_gainL_o <= st_gainL_i;
        end if; 
    end process;


    st_gainL_o_ap_vld_assign_proc : process(ng_pass_read_read_fu_62_p2, ap_CS_fsm_state3)
    begin
        if (((ng_pass_read_read_fu_62_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            st_gainL_o_ap_vld <= ap_const_logic_1;
        else 
            st_gainL_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    st_gainR_o_assign_proc : process(st_gainR_i, ng_pass_read_read_fu_62_p2, grp_core_Pipeline_MAIN_LOOP_fu_68_p_out, ap_CS_fsm_state3)
    begin
        if (((ng_pass_read_read_fu_62_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            st_gainR_o <= grp_core_Pipeline_MAIN_LOOP_fu_68_p_out;
        else 
            st_gainR_o <= st_gainR_i;
        end if; 
    end process;


    st_gainR_o_ap_vld_assign_proc : process(ng_pass_read_read_fu_62_p2, ap_CS_fsm_state3)
    begin
        if (((ng_pass_read_read_fu_62_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            st_gainR_o_ap_vld <= ap_const_logic_1;
        else 
            st_gainR_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    st_gate_openL_o_assign_proc : process(st_gate_openL_i, ng_pass_read_read_fu_62_p2, grp_core_Pipeline_MAIN_LOOP_fu_68_gateL_1_out, ap_CS_fsm_state3)
    begin
        if (((ng_pass_read_read_fu_62_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            st_gate_openL_o <= grp_core_Pipeline_MAIN_LOOP_fu_68_gateL_1_out;
        else 
            st_gate_openL_o <= st_gate_openL_i;
        end if; 
    end process;


    st_gate_openL_o_ap_vld_assign_proc : process(ng_pass_read_read_fu_62_p2, ap_CS_fsm_state3)
    begin
        if (((ng_pass_read_read_fu_62_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            st_gate_openL_o_ap_vld <= ap_const_logic_1;
        else 
            st_gate_openL_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    st_gate_openR_o_assign_proc : process(st_gate_openR_i, ng_pass_read_read_fu_62_p2, grp_core_Pipeline_MAIN_LOOP_fu_68_gateR_1_out, ap_CS_fsm_state3)
    begin
        if (((ng_pass_read_read_fu_62_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            st_gate_openR_o <= grp_core_Pipeline_MAIN_LOOP_fu_68_gateR_1_out;
        else 
            st_gate_openR_o <= st_gate_openR_i;
        end if; 
    end process;


    st_gate_openR_o_ap_vld_assign_proc : process(ng_pass_read_read_fu_62_p2, ap_CS_fsm_state3)
    begin
        if (((ng_pass_read_read_fu_62_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            st_gate_openR_o_ap_vld <= ap_const_logic_1;
        else 
            st_gate_openR_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

end behav;
