-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity audio_clean_up_dc_cut_Pipeline_MAIN_LOOP is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x1L : IN STD_LOGIC_VECTOR (33 downto 0);
    y1L : IN STD_LOGIC_VECTOR (33 downto 0);
    x1R : IN STD_LOGIC_VECTOR (33 downto 0);
    y1R : IN STD_LOGIC_VECTOR (33 downto 0);
    out_buf_data : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_buf_data_ap_vld : OUT STD_LOGIC;
    out_buf_id : OUT STD_LOGIC_VECTOR (2 downto 0);
    out_buf_id_ap_vld : OUT STD_LOGIC;
    in_buf_data_4_load_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    in_buf_data_3_load : IN STD_LOGIC_VECTOR (31 downto 0);
    in_buf_id_4_load_1 : IN STD_LOGIC_VECTOR (2 downto 0);
    in_buf_id_3_load : IN STD_LOGIC_VECTOR (2 downto 0);
    sext_ln37 : IN STD_LOGIC_VECTOR (23 downto 0);
    out_buf_data_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_buf_data_2_ap_vld : OUT STD_LOGIC;
    out_buf_id_2 : OUT STD_LOGIC_VECTOR (2 downto 0);
    out_buf_id_2_ap_vld : OUT STD_LOGIC;
    out_buf_id_2_load29_out : OUT STD_LOGIC_VECTOR (2 downto 0);
    out_buf_id_2_load29_out_ap_vld : OUT STD_LOGIC;
    out_buf_id_load24_out : OUT STD_LOGIC_VECTOR (2 downto 0);
    out_buf_id_load24_out_ap_vld : OUT STD_LOGIC;
    out_buf_data_2_load19_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_buf_data_2_load19_out_ap_vld : OUT STD_LOGIC;
    out_buf_data_load14_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_buf_data_load14_out_ap_vld : OUT STD_LOGIC;
    x1L_1_out : OUT STD_LOGIC_VECTOR (33 downto 0);
    x1L_1_out_ap_vld : OUT STD_LOGIC;
    y1L_1_out : OUT STD_LOGIC_VECTOR (33 downto 0);
    y1L_1_out_ap_vld : OUT STD_LOGIC;
    x1R_1_out : OUT STD_LOGIC_VECTOR (33 downto 0);
    x1R_1_out_ap_vld : OUT STD_LOGIC;
    y1R_1_out : OUT STD_LOGIC_VECTOR (33 downto 0);
    y1R_1_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of audio_clean_up_dc_cut_Pipeline_MAIN_LOOP is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv22_0 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv34_3FFF8000 : STD_LOGIC_VECTOR (33 downto 0) := "0000111111111111111000000000000000";
    constant ap_const_lv34_3C0000000 : STD_LOGIC_VECTOR (33 downto 0) := "1111000000000000000000000000000000";
    constant ap_const_lv31_3FFF8000 : STD_LOGIC_VECTOR (30 downto 0) := "0111111111111111000000000000000";
    constant ap_const_lv31_40000000 : STD_LOGIC_VECTOR (30 downto 0) := "1000000000000000000000000000000";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_FFFFC000 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111100000000000000";
    constant ap_const_lv32_4000 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000100000000000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln44_fu_350_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal grp_fu_310_p2 : STD_LOGIC_VECTOR (55 downto 0);
    signal reg_314 : STD_LOGIC_VECTOR (55 downto 0);
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal sext_ln37_cast_fu_318_p1 : STD_LOGIC_VECTOR (55 downto 0);
    signal sext_ln37_cast_reg_800 : STD_LOGIC_VECTOR (55 downto 0);
    signal icmp_ln44_reg_805 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_fu_362_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln47_reg_809 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln54_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln54_reg_814 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln68_fu_384_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln68_reg_823 : STD_LOGIC_VECTOR (0 downto 0);
    signal y1L_1_load_1_reg_827 : STD_LOGIC_VECTOR (33 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal sext_ln56_fu_408_p1 : STD_LOGIC_VECTOR (55 downto 0);
    signal y1R_1_load_1_reg_837 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln61_fu_416_p1 : STD_LOGIC_VECTOR (55 downto 0);
    signal sfin_data_fu_427_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sfin_data_reg_847 : STD_LOGIC_VECTOR (31 downto 0);
    signal y1L_2_reg_852 : STD_LOGIC_VECTOR (33 downto 0);
    signal sub_ln61_fu_484_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal sub_ln61_reg_858 : STD_LOGIC_VECTOR (33 downto 0);
    signal y_fu_548_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal y_reg_863 : STD_LOGIC_VECTOR (33 downto 0);
    signal ap_block_pp0_stage4_11001 : BOOLEAN;
    signal icmp_ln12_fu_554_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln12_reg_868 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln14_fu_560_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln14_reg_874 : STD_LOGIC_VECTOR (0 downto 0);
    signal y1R_1_fu_136 : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000000000000000000000000";
    signal y1R_3_fu_537_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal x1R_1_fu_140 : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000000000000000000000000";
    signal x1R_3_fu_490_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal y1L_1_fu_144 : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000000000000000000000000";
    signal y1L_3_fu_543_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal x1L_1_fu_148 : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000000000000000000000000";
    signal x1L_3_fu_497_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal i_fu_152 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal add_ln44_fu_356_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_i_2 : STD_LOGIC_VECTOR (1 downto 0);
    signal out_buf_data_load14_fu_156 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_buf_data_3_fu_674_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_buf_data_2_load19_fu_160 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_buf_id_load24_fu_164 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal out_buf_id_3_fu_368_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal out_buf_id_2_load29_fu_168 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal grp_fu_310_p0 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_310_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln56_fu_408_p0 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln61_fu_416_p0 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_5_fu_432_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_fu_442_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln51_fu_450_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sub_ln56_fu_454_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal shl_ln_fu_460_p3 : STD_LOGIC_VECTOR (55 downto 0);
    signal add_ln56_fu_468_p2 : STD_LOGIC_VECTOR (55 downto 0);
    signal ap_block_pp0_stage4 : BOOLEAN;
    signal shl_ln1_fu_514_p3 : STD_LOGIC_VECTOR (55 downto 0);
    signal add_ln61_fu_521_p2 : STD_LOGIC_VECTOR (55 downto 0);
    signal y1R_2_fu_527_p4 : STD_LOGIC_VECTOR (33 downto 0);
    signal or_ln12_fu_586_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln12_fu_579_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln52_fu_576_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal y_1_fu_590_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_fu_602_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln19_fu_610_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln6_fu_598_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_fu_618_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln22_fu_642_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_cast_fu_624_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln22_fu_646_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln22_fu_652_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_fu_634_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln22_fu_658_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln22_1_fu_666_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component audio_clean_up_mul_34s_24s_56_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (33 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (55 downto 0) );
    end component;


    component audio_clean_up_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_34s_24s_56_2_1_U12 : component audio_clean_up_mul_34s_24s_56_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 34,
        din1_WIDTH => 24,
        dout_WIDTH => 56)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_310_p0,
        din1 => grp_fu_310_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_310_p2);

    flow_control_loop_pipe_sequential_init_U : component audio_clean_up_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage4_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_152_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln44_fu_350_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_152 <= add_ln44_fu_356_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_152 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    x1L_1_fu_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                x1L_1_fu_148 <= x1L;
            elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (icmp_ln44_reg_805 = ap_const_lv1_0))) then 
                x1L_1_fu_148 <= x1L_3_fu_497_p3;
            end if; 
        end if;
    end process;

    x1R_1_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                x1R_1_fu_140 <= x1R;
            elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (icmp_ln44_reg_805 = ap_const_lv1_0))) then 
                x1R_1_fu_140 <= x1R_3_fu_490_p3;
            end if; 
        end if;
    end process;

    y1L_1_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                y1L_1_fu_144 <= y1L;
            elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (icmp_ln44_reg_805 = ap_const_lv1_0))) then 
                y1L_1_fu_144 <= y1L_3_fu_543_p3;
            end if; 
        end if;
    end process;

    y1R_1_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                y1R_1_fu_136 <= y1R;
            elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (icmp_ln44_reg_805 = ap_const_lv1_0))) then 
                y1R_1_fu_136 <= y1R_3_fu_537_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then
                icmp_ln12_reg_868 <= icmp_ln12_fu_554_p2;
                icmp_ln14_reg_874 <= icmp_ln14_fu_560_p2;
                y_reg_863 <= y_fu_548_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln44_reg_805 <= icmp_ln44_fu_350_p2;
                icmp_ln47_reg_809 <= icmp_ln47_fu_362_p2;
                icmp_ln54_reg_814 <= icmp_ln54_fu_378_p2;
                icmp_ln68_reg_823 <= icmp_ln68_fu_384_p2;
                sext_ln37_cast_reg_800 <= sext_ln37_cast_fu_318_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln68_reg_823 = ap_const_lv1_0))) then
                out_buf_data_2_load19_fu_160 <= out_buf_data_3_fu_674_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln68_reg_823 = ap_const_lv1_1))) then
                out_buf_data_load14_fu_156 <= out_buf_data_3_fu_674_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln44_fu_350_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln68_fu_384_p2 = ap_const_lv1_0))) then
                out_buf_id_2_load29_fu_168 <= out_buf_id_3_fu_368_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln44_fu_350_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln68_fu_384_p2 = ap_const_lv1_1))) then
                out_buf_id_load24_fu_164 <= out_buf_id_3_fu_368_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then
                reg_314 <= grp_fu_310_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                sfin_data_reg_847 <= sfin_data_fu_427_p3;
                sub_ln61_reg_858 <= sub_ln61_fu_484_p2;
                y1L_2_reg_852 <= add_ln56_fu_468_p2(55 downto 22);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                y1L_1_load_1_reg_827 <= y1L_1_fu_144;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                y1R_1_load_1_reg_837 <= y1R_1_fu_136;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter0_stage0, ap_block_pp0_stage4_subdone, ap_idle_pp0_1to1, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone, ap_block_pp0_stage3_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln22_fu_652_p2 <= std_logic_vector(unsigned(tmp_cast_fu_624_p4) + unsigned(ap_const_lv16_1));
    add_ln44_fu_356_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_2) + unsigned(ap_const_lv2_1));
    add_ln56_fu_468_p2 <= std_logic_vector(unsigned(shl_ln_fu_460_p3) + unsigned(reg_314));
    add_ln61_fu_521_p2 <= std_logic_vector(unsigned(shl_ln1_fu_514_p3) + unsigned(reg_314));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln44_fu_350_p2)
    begin
        if (((icmp_ln44_fu_350_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, i_fu_152)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_2 <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_i_2 <= i_fu_152;
        end if; 
    end process;


    grp_fu_310_p0_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, sext_ln56_fu_408_p1, sext_ln61_fu_416_p1, ap_block_pp0_stage2, ap_block_pp0_stage1)
    begin
        if ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                grp_fu_310_p0 <= sext_ln61_fu_416_p1(34 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_310_p0 <= sext_ln56_fu_408_p1(34 - 1 downto 0);
            else 
                grp_fu_310_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_fu_310_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_fu_310_p1 <= sext_ln37_cast_reg_800(24 - 1 downto 0);
    icmp_ln12_fu_554_p2 <= "1" when (signed(y_fu_548_p3) > signed(ap_const_lv34_3FFF8000)) else "0";
    icmp_ln14_fu_560_p2 <= "1" when (signed(y_fu_548_p3) < signed(ap_const_lv34_3C0000000)) else "0";
    icmp_ln22_fu_646_p2 <= "0" when (trunc_ln22_fu_642_p1 = ap_const_lv15_0) else "1";
    icmp_ln44_fu_350_p2 <= "1" when (ap_sig_allocacmp_i_2 = ap_const_lv2_2) else "0";
    icmp_ln47_fu_362_p2 <= "1" when (ap_sig_allocacmp_i_2 = ap_const_lv2_1) else "0";
    icmp_ln54_fu_378_p2 <= "1" when (out_buf_id_3_fu_368_p3 = ap_const_lv3_0) else "0";
    icmp_ln68_fu_384_p2 <= "1" when (ap_sig_allocacmp_i_2 = ap_const_lv2_0) else "0";
    or_ln12_fu_586_p2 <= (icmp_ln14_reg_874 or icmp_ln12_reg_868);
    out_buf_data <= out_buf_data_3_fu_674_p4;
    out_buf_data_2 <= out_buf_data_3_fu_674_p4;

    out_buf_data_2_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln68_reg_823)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln68_reg_823 = ap_const_lv1_0))) then 
            out_buf_data_2_ap_vld <= ap_const_logic_1;
        else 
            out_buf_data_2_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_buf_data_2_load19_out <= out_buf_data_2_load19_fu_160;

    out_buf_data_2_load19_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln44_fu_350_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln44_fu_350_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            out_buf_data_2_load19_out_ap_vld <= ap_const_logic_1;
        else 
            out_buf_data_2_load19_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_buf_data_3_fu_674_p4 <= (sfin_data_reg_847(31 downto 28) & select_ln22_1_fu_666_p3 & sfin_data_reg_847(11 downto 0));

    out_buf_data_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln68_reg_823)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln68_reg_823 = ap_const_lv1_1))) then 
            out_buf_data_ap_vld <= ap_const_logic_1;
        else 
            out_buf_data_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_buf_data_load14_out <= out_buf_data_load14_fu_156;

    out_buf_data_load14_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln44_fu_350_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln44_fu_350_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            out_buf_data_load14_out_ap_vld <= ap_const_logic_1;
        else 
            out_buf_data_load14_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_buf_id <= out_buf_id_3_fu_368_p3;
    out_buf_id_2 <= out_buf_id_3_fu_368_p3;

    out_buf_id_2_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln44_fu_350_p2, ap_block_pp0_stage0_11001, icmp_ln68_fu_384_p2)
    begin
        if (((icmp_ln44_fu_350_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln68_fu_384_p2 = ap_const_lv1_0))) then 
            out_buf_id_2_ap_vld <= ap_const_logic_1;
        else 
            out_buf_id_2_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_buf_id_2_load29_out <= out_buf_id_2_load29_fu_168;

    out_buf_id_2_load29_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln44_fu_350_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln44_fu_350_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            out_buf_id_2_load29_out_ap_vld <= ap_const_logic_1;
        else 
            out_buf_id_2_load29_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_buf_id_3_fu_368_p3 <= 
        in_buf_id_4_load_1 when (icmp_ln47_fu_362_p2(0) = '1') else 
        in_buf_id_3_load;

    out_buf_id_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln44_fu_350_p2, ap_block_pp0_stage0_11001, icmp_ln68_fu_384_p2)
    begin
        if (((icmp_ln44_fu_350_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln68_fu_384_p2 = ap_const_lv1_1))) then 
            out_buf_id_ap_vld <= ap_const_logic_1;
        else 
            out_buf_id_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_buf_id_load24_out <= out_buf_id_load24_fu_164;

    out_buf_id_load24_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln44_fu_350_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln44_fu_350_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            out_buf_id_load24_out_ap_vld <= ap_const_logic_1;
        else 
            out_buf_id_load24_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    r_fu_618_p2 <= std_logic_vector(unsigned(select_ln19_fu_610_p3) + unsigned(sext_ln6_fu_598_p1));
    select_ln12_fu_579_p3 <= 
        ap_const_lv31_3FFF8000 when (icmp_ln12_reg_868(0) = '1') else 
        ap_const_lv31_40000000;
    select_ln19_fu_610_p3 <= 
        ap_const_lv32_FFFFC000 when (tmp_fu_602_p3(0) = '1') else 
        ap_const_lv32_4000;
    select_ln22_1_fu_666_p3 <= 
        select_ln22_fu_658_p3 when (tmp_1_fu_634_p3(0) = '1') else 
        tmp_cast_fu_624_p4;
    select_ln22_fu_658_p3 <= 
        add_ln22_fu_652_p2 when (icmp_ln22_fu_646_p2(0) = '1') else 
        tmp_cast_fu_624_p4;
        sext_ln37_cast_fu_318_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln37),56));

        sext_ln51_fu_450_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(x_fu_442_p3),34));

    sext_ln56_fu_408_p0 <= y1L_1_fu_144;
        sext_ln56_fu_408_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln56_fu_408_p0),56));

    sext_ln61_fu_416_p0 <= y1R_1_fu_136;
        sext_ln61_fu_416_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln61_fu_416_p0),56));

        sext_ln6_fu_598_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(y_1_fu_590_p3),32));

    sfin_data_fu_427_p3 <= 
        in_buf_data_4_load_1 when (icmp_ln47_reg_809(0) = '1') else 
        in_buf_data_3_load;
    shl_ln1_fu_514_p3 <= (sub_ln61_reg_858 & ap_const_lv22_0);
    shl_ln_fu_460_p3 <= (sub_ln56_fu_454_p2 & ap_const_lv22_0);
    sub_ln56_fu_454_p2 <= std_logic_vector(signed(sext_ln51_fu_450_p1) - signed(x1L_1_fu_148));
    sub_ln61_fu_484_p2 <= std_logic_vector(signed(sext_ln51_fu_450_p1) - signed(x1R_1_fu_140));
    tmp_1_fu_634_p3 <= r_fu_618_p2(31 downto 31);
    tmp_5_fu_432_p4 <= sfin_data_fu_427_p3(27 downto 12);
    tmp_cast_fu_624_p4 <= r_fu_618_p2(30 downto 15);
    tmp_fu_602_p3 <= y_1_fu_590_p3(30 downto 30);
    trunc_ln22_fu_642_p1 <= r_fu_618_p2(15 - 1 downto 0);
    trunc_ln52_fu_576_p1 <= y_reg_863(31 - 1 downto 0);
    x1L_1_out <= x1L_1_fu_148;

    x1L_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln44_fu_350_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln44_fu_350_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x1L_1_out_ap_vld <= ap_const_logic_1;
        else 
            x1L_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    x1L_3_fu_497_p3 <= 
        sext_ln51_fu_450_p1 when (icmp_ln54_reg_814(0) = '1') else 
        x1L_1_fu_148;
    x1R_1_out <= x1R_1_fu_140;

    x1R_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln44_fu_350_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln44_fu_350_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x1R_1_out_ap_vld <= ap_const_logic_1;
        else 
            x1R_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    x1R_3_fu_490_p3 <= 
        x1R_1_fu_140 when (icmp_ln54_reg_814(0) = '1') else 
        sext_ln51_fu_450_p1;
    x_fu_442_p3 <= (tmp_5_fu_432_p4 & ap_const_lv15_0);
    y1L_1_out <= y1L_1_fu_144;

    y1L_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln44_fu_350_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln44_fu_350_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            y1L_1_out_ap_vld <= ap_const_logic_1;
        else 
            y1L_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    y1L_3_fu_543_p3 <= 
        y1L_2_reg_852 when (icmp_ln54_reg_814(0) = '1') else 
        y1L_1_load_1_reg_827;
    y1R_1_out <= y1R_1_fu_136;

    y1R_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln44_fu_350_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln44_fu_350_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            y1R_1_out_ap_vld <= ap_const_logic_1;
        else 
            y1R_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    y1R_2_fu_527_p4 <= add_ln61_fu_521_p2(55 downto 22);
    y1R_3_fu_537_p3 <= 
        y1R_1_load_1_reg_837 when (icmp_ln54_reg_814(0) = '1') else 
        y1R_2_fu_527_p4;
    y_1_fu_590_p3 <= 
        select_ln12_fu_579_p3 when (or_ln12_fu_586_p2(0) = '1') else 
        trunc_ln52_fu_576_p1;
    y_fu_548_p3 <= 
        y1L_2_reg_852 when (icmp_ln54_reg_814(0) = '1') else 
        y1R_2_fu_527_p4;
end behav;
