-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity audio_clean_up_core_Pipeline_MAIN_LOOP is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    gainR : IN STD_LOGIC_VECTOR (23 downto 0);
    gainL : IN STD_LOGIC_VECTOR (23 downto 0);
    gateL : IN STD_LOGIC_VECTOR (0 downto 0);
    gateR : IN STD_LOGIC_VECTOR (0 downto 0);
    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_9 : IN STD_LOGIC_VECTOR (31 downto 0);
    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_8 : IN STD_LOGIC_VECTOR (31 downto 0);
    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_11 : IN STD_LOGIC_VECTOR (2 downto 0);
    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_10 : IN STD_LOGIC_VECTOR (2 downto 0);
    th_close_amp : IN STD_LOGIC_VECTOR (33 downto 0);
    th_open_amp : IN STD_LOGIC_VECTOR (33 downto 0);
    a_att : IN STD_LOGIC_VECTOR (23 downto 0);
    a_rel : IN STD_LOGIC_VECTOR (23 downto 0);
    b_att : IN STD_LOGIC_VECTOR (23 downto 0);
    b_rel : IN STD_LOGIC_VECTOR (23 downto 0);
    p_out : OUT STD_LOGIC_VECTOR (23 downto 0);
    p_out_ap_vld : OUT STD_LOGIC;
    p_out1 : OUT STD_LOGIC_VECTOR (23 downto 0);
    p_out1_ap_vld : OUT STD_LOGIC;
    gateL_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    gateL_1_out_ap_vld : OUT STD_LOGIC;
    gateR_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    gateR_1_out_ap_vld : OUT STD_LOGIC;
    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld : OUT STD_LOGIC;
    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld : OUT STD_LOGIC;
    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld : OUT STD_LOGIC;
    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed : OUT STD_LOGIC_VECTOR (2 downto 0);
    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld : OUT STD_LOGIC );
end;


architecture behav of audio_clean_up_core_Pipeline_MAIN_LOOP is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv22_0 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    constant ap_const_lv46_0 : STD_LOGIC_VECTOR (45 downto 0) := "0000000000000000000000000000000000000000000000";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_2D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101101";
    constant ap_const_lv32_36 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    constant ap_const_lv33_3FFF8000 : STD_LOGIC_VECTOR (32 downto 0) := "000111111111111111000000000000000";
    constant ap_const_lv33_1C0000000 : STD_LOGIC_VECTOR (32 downto 0) := "111000000000000000000000000000000";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv31_3FFF8000 : STD_LOGIC_VECTOR (30 downto 0) := "0111111111111111000000000000000";
    constant ap_const_lv31_40000000 : STD_LOGIC_VECTOR (30 downto 0) := "1000000000000000000000000000000";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_FFFFC000 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111100000000000000";
    constant ap_const_lv32_4000 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000100000000000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln51_reg_835 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage2 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal gateL_1_reg_276 : STD_LOGIC_VECTOR (0 downto 0);
    signal gateR_1_reg_287 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln51_fu_334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_reg_835_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sfin_data_fu_352_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sfin_data_reg_839 : STD_LOGIC_VECTOR (31 downto 0);
    signal sfin_data_reg_839_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_reg_844 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_reg_849 : STD_LOGIC_VECTOR (0 downto 0);
    signal isL_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal isL_reg_854 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln92_fu_392_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln92_reg_866 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln92_reg_866_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_fu_415_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal x_reg_870 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal gateon_3_fu_462_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal gateon_3_reg_875 : STD_LOGIC_VECTOR (0 downto 0);
    signal gainL_1_load_reg_884 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal gainR_1_load_reg_889 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln79_fu_298_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal mul_ln79_reg_894 : STD_LOGIC_VECTOR (45 downto 0);
    signal gain_1_fu_529_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal gain_1_reg_899 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal gateR_2_fu_565_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal gateR_2_reg_904 : STD_LOGIC_VECTOR (0 downto 0);
    signal gateL_2_fu_571_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal gateL_2_reg_909 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage4_11001 : BOOLEAN;
    signal grp_fu_302_p2 : STD_LOGIC_VECTOR (54 downto 0);
    signal mul_ln89_reg_924 : STD_LOGIC_VECTOR (54 downto 0);
    signal trunc_ln_reg_929 : STD_LOGIC_VECTOR (32 downto 0);
    signal icmp_ln16_fu_615_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln16_reg_935 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln18_fu_620_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln18_reg_941 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_gateL_1_phi_fu_280_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_phi_mux_gateR_1_phi_fu_291_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal sfout_data_2_fu_729_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal sfin_id_fu_360_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal empty_fu_144 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal select_ln81_3_fu_558_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal empty_43_fu_148 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal select_ln81_2_fu_551_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal i_fu_152 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal add_ln51_fu_340_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_i_4 : STD_LOGIC_VECTOR (1 downto 0);
    signal gainL_1_fu_156 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal gainL_2_fu_545_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal gainR_1_fu_160 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal gainR_2_fu_539_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage2_01001 : BOOLEAN;
    signal ap_block_pp0_stage4 : BOOLEAN;
    signal icmp_ln54_fu_346_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal level_fu_422_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal level_1_fu_428_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln58_fu_435_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal icmp_ln69_fu_451_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal gateon_fu_439_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal gateon_1_fu_446_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal gateon_2_fu_456_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal a_fu_483_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal gain_fu_476_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal select_ln76_fu_504_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal shl_ln_fu_509_p3 : STD_LOGIC_VECTOR (45 downto 0);
    signal select_ln79_fu_517_p3 : STD_LOGIC_VECTOR (45 downto 0);
    signal add_ln79_fu_524_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal or_ln16_fu_641_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln16_fu_634_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln89_1_fu_625_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal y_fu_645_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_3_fu_657_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln22_fu_665_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln11_fu_653_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_fu_673_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln23_fu_697_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_cast_fu_679_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln23_fu_701_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln23_fu_707_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_fu_689_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln23_fu_713_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln23_1_fu_721_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component audio_clean_up_mul_24s_24s_46_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (23 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        dout : OUT STD_LOGIC_VECTOR (45 downto 0) );
    end component;


    component audio_clean_up_mul_31s_24s_55_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (30 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (54 downto 0) );
    end component;


    component audio_clean_up_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_24s_24s_46_1_1_U65 : component audio_clean_up_mul_24s_24s_46_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 24,
        din1_WIDTH => 24,
        dout_WIDTH => 46)
    port map (
        din0 => a_fu_483_p3,
        din1 => gain_fu_476_p3,
        dout => mul_ln79_fu_298_p2);

    mul_31s_24s_55_2_1_U66 : component audio_clean_up_mul_31s_24s_55_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 31,
        din1_WIDTH => 24,
        dout_WIDTH => 55)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => x_reg_870,
        din1 => gain_1_reg_899,
        ce => ap_const_logic_1,
        dout => grp_fu_302_p2);

    flow_control_loop_pipe_sequential_init_U : component audio_clean_up_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage2,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage2)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage4_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    empty_43_fu_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                empty_43_fu_148 <= gainR;
            elsif (((icmp_ln51_reg_835 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                empty_43_fu_148 <= select_ln81_2_fu_551_p3;
            end if; 
        end if;
    end process;

    empty_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                empty_fu_144 <= gainL;
            elsif (((icmp_ln51_reg_835 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                empty_fu_144 <= select_ln81_3_fu_558_p3;
            end if; 
        end if;
    end process;

    gainL_1_fu_156_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                gainL_1_fu_156 <= gainL;
            elsif (((icmp_ln51_reg_835 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                gainL_1_fu_156 <= gainL_2_fu_545_p3;
            end if; 
        end if;
    end process;

    gainR_1_fu_160_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                gainR_1_fu_160 <= gainR;
            elsif (((icmp_ln51_reg_835 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                gainR_1_fu_160 <= gainR_2_fu_539_p3;
            end if; 
        end if;
    end process;

    gateL_1_reg_276_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                gateL_1_reg_276 <= gateL;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln51_reg_835_pp0_iter1_reg = ap_const_lv1_0))) then 
                gateL_1_reg_276 <= gateL_2_reg_909;
            end if; 
        end if;
    end process;

    gateR_1_reg_287_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                gateR_1_reg_287 <= gateR;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln51_reg_835_pp0_iter1_reg = ap_const_lv1_0))) then 
                gateR_1_reg_287 <= gateR_2_reg_904;
            end if; 
        end if;
    end process;

    i_fu_152_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln51_fu_334_p2 = ap_const_lv1_0))) then 
                    i_fu_152 <= add_ln51_fu_340_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_152 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                gainL_1_load_reg_884 <= gainL_1_fu_156;
                gainR_1_load_reg_889 <= gainR_1_fu_160;
                mul_ln79_reg_894 <= mul_ln79_fu_298_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                gain_1_reg_899 <= add_ln79_fu_524_p2(45 downto 22);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                gateL_2_reg_909 <= gateL_2_fu_571_p3;
                gateR_2_reg_904 <= gateR_2_fu_565_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                gateon_3_reg_875 <= gateon_3_fu_462_p3;
                icmp_ln16_reg_935 <= icmp_ln16_fu_615_p2;
                icmp_ln18_reg_941 <= icmp_ln18_fu_620_p2;
                    x_reg_870(30 downto 15) <= x_fu_415_p3(30 downto 15);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln51_reg_835 <= icmp_ln51_fu_334_p2;
                icmp_ln51_reg_835_pp0_iter1_reg <= icmp_ln51_reg_835;
                icmp_ln92_reg_866 <= icmp_ln92_fu_392_p2;
                icmp_ln92_reg_866_pp0_iter1_reg <= icmp_ln92_reg_866;
                isL_reg_854 <= isL_fu_386_p2;
                mul_ln89_reg_924 <= grp_fu_302_p2;
                sfin_data_reg_839 <= sfin_data_fu_352_p3;
                sfin_data_reg_839_pp0_iter1_reg <= sfin_data_reg_839;
                tmp_2_reg_849 <= sfin_data_fu_352_p3(27 downto 27);
                tmp_reg_844 <= sfin_data_fu_352_p3(27 downto 12);
                trunc_ln_reg_929 <= grp_fu_302_p2(54 downto 22);
            end if;
        end if;
    end process;
    x_reg_870(14 downto 0) <= "000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage2_subdone, ap_condition_exit_pp0_iter0_stage2, ap_block_pp0_stage4_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to1, ap_block_pp0_stage1_subdone, ap_block_pp0_stage3_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage2)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    a_fu_483_p3 <= 
        a_att when (gateon_3_reg_875(0) = '1') else 
        a_rel;
    add_ln23_fu_707_p2 <= std_logic_vector(unsigned(tmp_cast_fu_679_p4) + unsigned(ap_const_lv16_1));
    add_ln51_fu_340_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_4) + unsigned(ap_const_lv2_1));
    add_ln79_fu_524_p2 <= std_logic_vector(unsigned(mul_ln79_reg_894) + unsigned(select_ln79_fu_517_p3));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage2_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln51_reg_835)
    begin
        if (((icmp_ln51_reg_835 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage2;

    ap_phi_mux_gateL_1_phi_fu_280_p4_assign_proc : process(ap_enable_reg_pp0_iter1, gateL_1_reg_276, icmp_ln51_reg_835_pp0_iter1_reg, ap_CS_fsm_pp0_stage1, gateL_2_reg_909, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln51_reg_835_pp0_iter1_reg = ap_const_lv1_0))) then 
            ap_phi_mux_gateL_1_phi_fu_280_p4 <= gateL_2_reg_909;
        else 
            ap_phi_mux_gateL_1_phi_fu_280_p4 <= gateL_1_reg_276;
        end if; 
    end process;


    ap_phi_mux_gateR_1_phi_fu_291_p4_assign_proc : process(ap_enable_reg_pp0_iter1, gateR_1_reg_287, icmp_ln51_reg_835_pp0_iter1_reg, ap_CS_fsm_pp0_stage1, gateR_2_reg_904, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln51_reg_835_pp0_iter1_reg = ap_const_lv1_0))) then 
            ap_phi_mux_gateR_1_phi_fu_291_p4 <= gateR_2_reg_904;
        else 
            ap_phi_mux_gateR_1_phi_fu_291_p4 <= gateR_1_reg_287;
        end if; 
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, i_fu_152)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_4 <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_i_4 <= i_fu_152;
        end if; 
    end process;

    gainL_2_fu_545_p3 <= 
        gain_1_fu_529_p4 when (isL_reg_854(0) = '1') else 
        gainL_1_load_reg_884;
    gainR_2_fu_539_p3 <= 
        gainR_1_load_reg_889 when (isL_reg_854(0) = '1') else 
        gain_1_fu_529_p4;
    gain_1_fu_529_p4 <= add_ln79_fu_524_p2(45 downto 22);
    gain_fu_476_p3 <= 
        gainL_1_fu_156 when (isL_reg_854(0) = '1') else 
        gainR_1_fu_160;
    gateL_1_out <= gateL_1_reg_276;

    gateL_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage2, icmp_ln51_reg_835, ap_loop_exit_ready, ap_block_pp0_stage2_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln51_reg_835 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            gateL_1_out_ap_vld <= ap_const_logic_1;
        else 
            gateL_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    gateL_2_fu_571_p3 <= 
        gateon_3_reg_875 when (isL_reg_854(0) = '1') else 
        gateL_1_reg_276;
    gateR_1_out <= gateR_1_reg_287;

    gateR_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage2, icmp_ln51_reg_835, ap_loop_exit_ready, ap_block_pp0_stage2_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln51_reg_835 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            gateR_1_out_ap_vld <= ap_const_logic_1;
        else 
            gateR_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    gateR_2_fu_565_p3 <= 
        gateR_1_reg_287 when (isL_reg_854(0) = '1') else 
        gateon_3_reg_875;
    gateon_1_fu_446_p2 <= "1" when (signed(zext_ln58_fu_435_p1) > signed(th_close_amp)) else "0";
    gateon_2_fu_456_p2 <= (icmp_ln69_fu_451_p2 xor ap_const_lv1_1);
    gateon_3_fu_462_p3 <= 
        gateon_1_fu_446_p2 when (gateon_fu_439_p3(0) = '1') else 
        gateon_2_fu_456_p2;
    gateon_fu_439_p3 <= 
        ap_phi_mux_gateL_1_phi_fu_280_p4 when (isL_reg_854(0) = '1') else 
        ap_phi_mux_gateR_1_phi_fu_291_p4;
    icmp_ln16_fu_615_p2 <= "1" when (signed(trunc_ln_reg_929) > signed(ap_const_lv33_3FFF8000)) else "0";
    icmp_ln18_fu_620_p2 <= "1" when (signed(trunc_ln_reg_929) < signed(ap_const_lv33_1C0000000)) else "0";
    icmp_ln23_fu_701_p2 <= "0" when (trunc_ln23_fu_697_p1 = ap_const_lv15_0) else "1";
    icmp_ln51_fu_334_p2 <= "1" when (ap_sig_allocacmp_i_4 = ap_const_lv2_2) else "0";
    icmp_ln54_fu_346_p2 <= "1" when (ap_sig_allocacmp_i_4 = ap_const_lv2_1) else "0";
    icmp_ln69_fu_451_p2 <= "1" when (signed(zext_ln58_fu_435_p1) < signed(th_open_amp)) else "0";
    icmp_ln92_fu_392_p2 <= "1" when (ap_sig_allocacmp_i_4 = ap_const_lv2_0) else "0";
    isL_fu_386_p2 <= "1" when (sfin_id_fu_360_p3 = ap_const_lv3_0) else "0";
    level_1_fu_428_p3 <= 
        level_fu_422_p2 when (tmp_2_reg_849(0) = '1') else 
        x_fu_415_p3;
    level_fu_422_p2 <= std_logic_vector(unsigned(ap_const_lv31_0) - unsigned(x_fu_415_p3));
    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed <= sfin_id_fu_360_p3;
    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1 <= sfin_id_fu_360_p3;

    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001, icmp_ln51_fu_334_p2, icmp_ln92_fu_392_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln92_fu_392_p2 = ap_const_lv1_1) and (icmp_ln51_fu_334_p2 = ap_const_lv1_0))) then 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld <= ap_const_logic_1;
        else 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2 <= sfout_data_2_fu_729_p4;

    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, icmp_ln92_reg_866_pp0_iter1_reg, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (icmp_ln92_reg_866_pp0_iter1_reg = ap_const_lv1_0))) then 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld <= ap_const_logic_1;
        else 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_2_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3 <= sfout_data_2_fu_729_p4;

    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, icmp_ln92_reg_866_pp0_iter1_reg, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (icmp_ln92_reg_866_pp0_iter1_reg = ap_const_lv1_1))) then 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld <= ap_const_logic_1;
        else 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_3_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001, icmp_ln51_fu_334_p2, icmp_ln92_fu_392_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln92_fu_392_p2 = ap_const_lv1_0) and (icmp_ln51_fu_334_p2 = ap_const_lv1_0))) then 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld <= ap_const_logic_1;
        else 
            noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    or_ln16_fu_641_p2 <= (icmp_ln18_reg_941 or icmp_ln16_reg_935);
    p_out <= empty_43_fu_148;
    p_out1 <= empty_fu_144;

    p_out1_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage2, icmp_ln51_reg_835, ap_loop_exit_ready, ap_block_pp0_stage2_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln51_reg_835 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            p_out1_ap_vld <= ap_const_logic_1;
        else 
            p_out1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage2, icmp_ln51_reg_835, ap_loop_exit_ready, ap_block_pp0_stage2_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln51_reg_835 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            p_out_ap_vld <= ap_const_logic_1;
        else 
            p_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    r_fu_673_p2 <= std_logic_vector(unsigned(select_ln22_fu_665_p3) + unsigned(sext_ln11_fu_653_p1));
    select_ln16_fu_634_p3 <= 
        ap_const_lv31_3FFF8000 when (icmp_ln16_reg_935(0) = '1') else 
        ap_const_lv31_40000000;
    select_ln22_fu_665_p3 <= 
        ap_const_lv32_FFFFC000 when (tmp_3_fu_657_p3(0) = '1') else 
        ap_const_lv32_4000;
    select_ln23_1_fu_721_p3 <= 
        select_ln23_fu_713_p3 when (tmp_4_fu_689_p3(0) = '1') else 
        tmp_cast_fu_679_p4;
    select_ln23_fu_713_p3 <= 
        add_ln23_fu_707_p2 when (icmp_ln23_fu_701_p2(0) = '1') else 
        tmp_cast_fu_679_p4;
    select_ln76_fu_504_p3 <= 
        b_att when (gateon_3_reg_875(0) = '1') else 
        b_rel;
    select_ln79_fu_517_p3 <= 
        shl_ln_fu_509_p3 when (gateon_3_reg_875(0) = '1') else 
        ap_const_lv46_0;
    select_ln81_2_fu_551_p3 <= 
        empty_43_fu_148 when (isL_reg_854(0) = '1') else 
        gain_1_fu_529_p4;
    select_ln81_3_fu_558_p3 <= 
        gain_1_fu_529_p4 when (isL_reg_854(0) = '1') else 
        empty_fu_144;
        sext_ln11_fu_653_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(y_fu_645_p3),32));

    sfin_data_fu_352_p3 <= 
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_9 when (icmp_ln54_fu_346_p2(0) = '1') else 
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_8;
    sfin_id_fu_360_p3 <= 
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_11 when (icmp_ln54_fu_346_p2(0) = '1') else 
        noise_gate_stream_stream_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_ap_fixed_10;
    sfout_data_2_fu_729_p4 <= (sfin_data_reg_839_pp0_iter1_reg(31 downto 28) & select_ln23_1_fu_721_p3 & sfin_data_reg_839_pp0_iter1_reg(11 downto 0));
    shl_ln_fu_509_p3 <= (select_ln76_fu_504_p3 & ap_const_lv22_0);
    tmp_3_fu_657_p3 <= y_fu_645_p3(30 downto 30);
    tmp_4_fu_689_p3 <= r_fu_673_p2(31 downto 31);
    tmp_cast_fu_679_p4 <= r_fu_673_p2(30 downto 15);
    trunc_ln23_fu_697_p1 <= r_fu_673_p2(15 - 1 downto 0);
    trunc_ln89_1_fu_625_p4 <= mul_ln89_reg_924(52 downto 22);
    x_fu_415_p3 <= (tmp_reg_844 & ap_const_lv15_0);
    y_fu_645_p3 <= 
        select_ln16_fu_634_p3 when (or_ln16_fu_641_p2(0) = '1') else 
        trunc_ln89_1_fu_625_p4;
    zext_ln58_fu_435_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(level_1_fu_428_p3),34));
end behav;
